#
# Copyright 2024 Ettus Research, a National Instruments Brand
#
# SPDX-License-Identifier: LGPL-3.0-or-later
#
# Description:
#
#   This template defines a stages-based pipeline for building X410 and X440 FPGA.
#
#   See https://aka.ms/yaml for pipeline YAML documentation.
#

parameters:
## Optional parameters
# Option to ignore cached artifacts (if available) and perform
# a clean IP build.
- name: clean_ip_build
  type: boolean
  default: false
# Number of parallel jobs to use for IP build
- name: num_ip_jobs
  type: number
  default: 5
# Option to publish intermediate files
- name: publish_int_files
  type: boolean
  default: false
# Package and publish images
- name: package_and_publish_images
  type: boolean
  default: true
# Package access in the SDR server ('Internal' or 'Public')
- name: package_access
  type: string
  default: 'Internal'
# From where to pull FPGA bitfiles if we're not building them
- name: fpga_imgs_source
  type: string
  default: 'Mono Pipeline'
# X410 FPGA targets to build
- name: x410_targets_matrix
  type: object
  default: {}
# X440 FPGA targets to build
- name: x440_targets_matrix
  type: object
  default: {}
- name: additional_setup_steps
  type: stepList
  default: []
- name: rfnoc_include_dir
  type: string
  default: ""
  displayName: RFNoC OOT module path

stages:

### START: X410 stages

- stage: provide_x410_fpga_images_stage
  displayName: Provide X410 FPGA Images
  dependsOn: analyze_changeset
  variables:
    BuildRequired: $[or(
                    contains(stageDependencies.analyze_changeset.analyze.outputs['gen_testlist.UhdTestList'], 'fpga.usrp3.x410'),
                    contains(stageDependencies.analyze_changeset.analyze.outputs['gen_testlist.UhdTestList'], 'fpga.usrp3.x4xx'),
                    contains(stageDependencies.analyze_changeset.analyze.outputs['gen_testlist.UhdTestList'], 'fpga.usrp3.all')
                  )]
  jobs:
  - template: ../templates/jobs-provide-fpga-artifacts.yml
    parameters:
      id: x410
      device_name: X410
      ip_target: X410_IP
      package_name: x4xx_x410_fpga_default
      clean_ip_build: ${{ parameters.clean_ip_build }}
      num_ip_jobs: ${{ parameters.num_ip_jobs }}
      publish_int_files: ${{ parameters.publish_int_files }}
      package_and_publish_images: ${{ parameters.package_and_publish_images }}
      package_access: ${{ parameters.package_access }}
      fpga_imgs_source: ${{ parameters.fpga_imgs_source }}
      top_dir: uhddev/fpga/usrp3/top/x400
      target_full_matrix: ${{ parameters.x410_targets_matrix }}
      target_reduced_matrix: ${{ parameters.x410_targets_matrix }}
      additional_setup_steps: ${{ parameters.additional_setup_steps }}
      rfnoc_include_dir: ${{ parameters.rfnoc_include_dir }}

- stage: provide_x440_fpga_images_stage
  displayName: Provide X440 FPGA Images
  dependsOn: analyze_changeset
  variables:
    BuildRequired: $[or(
                    contains(stageDependencies.analyze_changeset.analyze.outputs['gen_testlist.UhdTestList'], 'fpga.usrp3.x440'),
                    contains(stageDependencies.analyze_changeset.analyze.outputs['gen_testlist.UhdTestList'], 'fpga.usrp3.x4xx'),
                    contains(stageDependencies.analyze_changeset.analyze.outputs['gen_testlist.UhdTestList'], 'fpga.usrp3.all')
                  )]
  jobs:
  - template: ../templates/jobs-provide-fpga-artifacts.yml
    parameters:
      id: x440
      device_name: X440
      ip_target: X440_IP
      package_name: x4xx_x440_fpga_default
      clean_ip_build: ${{ parameters.clean_ip_build }}
      num_ip_jobs: ${{ parameters.num_ip_jobs }}
      publish_int_files: ${{ parameters.publish_int_files }}
      package_and_publish_images: ${{ parameters.package_and_publish_images }}
      package_access: ${{ parameters.package_access }}
      fpga_imgs_source: ${{ parameters.fpga_imgs_source }}
      top_dir: uhddev/fpga/usrp3/top/x400
      target_full_matrix: ${{ parameters.x440_targets_matrix }}
      target_reduced_matrix: ${{ parameters.x440_targets_matrix }}
      additional_setup_steps: ${{ parameters.additional_setup_steps }}
      rfnoc_include_dir: ${{ parameters.rfnoc_include_dir }}


### END: X440 stages
