#
# Copyright 2025 Ettus Research, a National Instruments Brand
#
# SPDX-License-Identifier: LGPL-3.0-or-later
#


######################################################################################
# Pin Location Information
######################################################################################

#  CLOCKS
set_property PACKAGE_PIN F6 [get_ports PCIE_REF_CLK_P]
set_property PACKAGE_PIN F5 [get_ports PCIE_REF_CLK_N]

set_property PACKAGE_PIN AB17 [get_ports DEVCLK_P]
set_property PACKAGE_PIN AC17 [get_ports DEVCLK_N]

set_property PACKAGE_PIN AD18 [get_ports FPGA_REFCLK_N]
set_property PACKAGE_PIN AC18 [get_ports FPGA_REFCLK_P]
set_property PACKAGE_PIN AC16 [get_ports EXT_REFCLK_N]
set_property PACKAGE_PIN AB16 [get_ports EXT_REFCLK_P]
set_property PACKAGE_PIN K5   [get_ports JESD_CLK_N]
set_property PACKAGE_PIN K6   [get_ports JESD_CLK_P]
set_property PACKAGE_PIN AA18 [get_ports SYSREF_N]
set_property PACKAGE_PIN AA17 [get_ports SYSREF_P]

# RESETS

set_property PACKAGE_PIN A15 [get_ports PCIE_PRESENT_N]
set_property PACKAGE_PIN K21 [get_ports PCIE_RESET_N]

set_property PACKAGE_PIN H26  [get_ports PG_1V2]
set_property PACKAGE_PIN E16  [get_ports TYPEC_PWR_NEGOTIATED]
set_property PACKAGE_PIN K17  [get_ports VBUS_ALERT_N]
set_property PACKAGE_PIN B15  [get_ports GT_25W_PWR_SRC]

set_property PACKAGE_PIN V26  [get_ports {ADRV_GPINT[0]}]
set_property PACKAGE_PIN Y26  [get_ports {ADRV_GPINT[1]}]
set_property PACKAGE_PIN B19  [get_ports {ADRV_GPIO[0]}]
set_property PACKAGE_PIN E21  [get_ports {ADRV_GPIO[1]}]
set_property PACKAGE_PIN F23  [get_ports {ADRV_GPIO[2]}]
set_property PACKAGE_PIN E23  [get_ports {ADRV_GPIO[3]}]
set_property PACKAGE_PIN F22  [get_ports {ADRV_GPIO[4]}]
set_property PACKAGE_PIN C23  [get_ports {ADRV_GPIO[5]}]
set_property PACKAGE_PIN AE23 [get_ports {ADRV_GPIO[6]}]
set_property PACKAGE_PIN AE22 [get_ports {ADRV_GPIO[7]}]
set_property PACKAGE_PIN D23  [get_ports ADRV_ORXA_CTRL]
set_property PACKAGE_PIN AC21 [get_ports ADRV_ORXB_CTRL]
set_property PACKAGE_PIN E26  [get_ports ADRV_RESET_N]
set_property PACKAGE_PIN J25  [get_ports ADRV_SPI_CLK]
set_property PACKAGE_PIN AA25 [get_ports ADRV_SPI_DIO]
set_property PACKAGE_PIN AE26 [get_ports ADRV_SPI_DO]
set_property PACKAGE_PIN W25  [get_ports ADRV_SPI_EN_N]
set_property PACKAGE_PIN AB20 [get_ports {ADRV_SYNCIN_N[0]}]
set_property PACKAGE_PIN AE20 [get_ports {ADRV_SYNCIN_N[1]}]
set_property PACKAGE_PIN AA20 [get_ports {ADRV_SYNCIN_N[2]}]
set_property PACKAGE_PIN AB19 [get_ports {ADRV_SYNCIN_P[0]}]
set_property PACKAGE_PIN AD20 [get_ports {ADRV_SYNCIN_P[1]}]
set_property PACKAGE_PIN AA19 [get_ports {ADRV_SYNCIN_P[2]}]
set_property PACKAGE_PIN AD19 [get_ports {ADRV_SYNCOUT_N[0]}]
set_property PACKAGE_PIN AB15 [get_ports {ADRV_SYNCOUT_N[1]}]
set_property PACKAGE_PIN AC19 [get_ports {ADRV_SYNCOUT_P[0]}]
set_property PACKAGE_PIN AB14 [get_ports {ADRV_SYNCOUT_P[1]}]
set_property PACKAGE_PIN Y25  [get_ports ADRV_TEST_EN]
set_property PACKAGE_PIN C19  [get_ports ADRV_TRXA_CTRL]
set_property PACKAGE_PIN A19  [get_ports ADRV_TRXB_CTRL]
set_property PACKAGE_PIN F24  [get_ports ADRV_TRXC_CTRL]
set_property PACKAGE_PIN D24  [get_ports ADRV_TRXD_CTRL]
set_property PACKAGE_PIN AD21 [get_ports ADRV_TRXE_CTRL]
set_property PACKAGE_PIN AF22 [get_ports ADRV_TRXF_CTRL]
set_property PACKAGE_PIN AC22 [get_ports ADRV_TRXG_CTRL]
set_property PACKAGE_PIN AF23 [get_ports ADRV_TRXH_CTRL]

set_property PACKAGE_PIN U24  [get_ports JTAG_CPLD_TCK]
set_property PACKAGE_PIN U26  [get_ports JTAG_CPLD_TDI]
set_property PACKAGE_PIN J26  [get_ports JTAG_CPLD_TDO]
set_property PACKAGE_PIN U25  [get_ports JTAG_CPLD_TMS]
set_property PACKAGE_PIN V13  [get_ports JTAG_TBOLT_TCK]
set_property PACKAGE_PIN M16  [get_ports JTAG_TBOLT_TDI]
set_property PACKAGE_PIN D15  [get_ports JTAG_TBOLT_TDO]
set_property PACKAGE_PIN L17  [get_ports JTAG_TBOLT_TMS]

set_property PACKAGE_PIN T20  [get_ports LMK32_CS_N]
set_property PACKAGE_PIN T22  [get_ports LMK32_MISO]
set_property PACKAGE_PIN U19  [get_ports LMK32_MOSI]
set_property PACKAGE_PIN P19  [get_ports LMK32_RESET]
set_property PACKAGE_PIN T18  [get_ports LMK32_SCLK]
set_property PACKAGE_PIN R22  [get_ports LMK32_STATUS]
set_property PACKAGE_PIN U20  [get_ports LMK32_VCXO_SEL_122M88]
set_property PACKAGE_PIN T24  [get_ports LMK053_CS_N]
set_property PACKAGE_PIN R25  [get_ports LMK053_MISO]
set_property PACKAGE_PIN R26  [get_ports LMK053_MOSI]
set_property PACKAGE_PIN R23  [get_ports LMK053_SCLK]
set_property PACKAGE_PIN AF15 [get_ports LMK_SYNC_REVA]
set_property PACKAGE_PIN P18  [get_ports LMK_SYNC]

set_property PACKAGE_PIN R21  [get_ports GPS_PPS_OUT]
set_property PACKAGE_PIN N24  [get_ports GPS_PWR_FAULT_N]
set_property PACKAGE_PIN Y23  [get_ports {GPS_REF[0]}]
set_property PACKAGE_PIN Y22  [get_ports {GPS_REF[1]}]
set_property PACKAGE_PIN N26  [get_ports GPS_REFSEL]
set_property PACKAGE_PIN M26  [get_ports GPS_RESET_N]
set_property PACKAGE_PIN AF20 [get_ports GPS_SECREF_N]
set_property PACKAGE_PIN AF19 [get_ports GPS_SECREF_P]
set_property PACKAGE_PIN K25  [get_ports GPS_EXTINT]
set_property PACKAGE_PIN T25  [get_ports GPS_UART_TOFPGA]
set_property PACKAGE_PIN T23  [get_ports GPS_UART_TOGPS]

set_property PACKAGE_PIN E15  [get_ports CPLD_EXT_RST_R_N]
set_property PACKAGE_PIN F25  [get_ports CPLD_OSC_EN]
set_property PACKAGE_PIN G17  [get_ports CPLD_RX_CLK]
set_property PACKAGE_PIN B17  [get_ports CPLD_RX_CLKEN]
set_property PACKAGE_PIN G15  [get_ports {CPLD_RX_DATA[0]}]
set_property PACKAGE_PIN J15  [get_ports {CPLD_RX_DATA[1]}]
set_property PACKAGE_PIN G19  [get_ports {CPLD_RX_DATA[2]}]
set_property PACKAGE_PIN H18  [get_ports {CPLD_RX_DATA[3]}]
set_property PACKAGE_PIN A17  [get_ports {CPLD_RX_DATA[4]}]
set_property PACKAGE_PIN D18  [get_ports {CPLD_RX_DATA[5]}]
set_property PACKAGE_PIN J16  [get_ports {CPLD_RX_DATA[6]}]
set_property PACKAGE_PIN D19  [get_ports {CPLD_RX_DATA[7]}]
set_property PACKAGE_PIN E18  [get_ports CPLD_TX_CLK]
set_property PACKAGE_PIN F20  [get_ports CPLD_TX_CLKEN]
set_property PACKAGE_PIN H17  [get_ports {CPLD_TX_DATA[0]}]
set_property PACKAGE_PIN H16  [get_ports {CPLD_TX_DATA[1]}]
set_property PACKAGE_PIN D20  [get_ports {CPLD_TX_DATA[2]}]
set_property PACKAGE_PIN F15  [get_ports {CPLD_TX_DATA[3]}]
set_property PACKAGE_PIN F19  [get_ports {CPLD_TX_DATA[4]}]
set_property PACKAGE_PIN E20  [get_ports {CPLD_TX_DATA[5]}]
set_property PACKAGE_PIN H19  [get_ports {CPLD_TX_DATA[6]}]
set_property PACKAGE_PIN G20  [get_ports {CPLD_TX_DATA[7]}]
set_property PACKAGE_PIN D25  [get_ports PCIE_RESET_N_TO_CPLD]


set_property PACKAGE_PIN B10  [get_ports {FP_GPIO[0]}]
set_property PACKAGE_PIN A9   [get_ports {FP_GPIO[1]}]
set_property PACKAGE_PIN D9   [get_ports {FP_GPIO[2]}]
set_property PACKAGE_PIN A13  [get_ports {FP_GPIO[3]}]
set_property PACKAGE_PIN B11  [get_ports {FP_GPIO[4]}]
set_property PACKAGE_PIN A10  [get_ports {FP_GPIO[5]}]
set_property PACKAGE_PIN B9   [get_ports {FP_GPIO[6]}]
set_property PACKAGE_PIN C9   [get_ports {FP_GPIO[7]}]
set_property PACKAGE_PIN A12  [get_ports {FP_GPIO[8]}]
set_property PACKAGE_PIN B12  [get_ports {FP_GPIO[9]}]

set_property PACKAGE_PIN W13  [get_ports LED_CLK_STS_GRN]
set_property PACKAGE_PIN AA15 [get_ports LED_PWR_STS_BLUE]
set_property PACKAGE_PIN AC14 [get_ports LED_PWR_STS_ORANGE]
set_property PACKAGE_PIN AB25 [get_ports {LED_TX_GRN[0]}]
set_property PACKAGE_PIN AC26 [get_ports {LED_TX_GRN[1]}]
set_property PACKAGE_PIN AB22 [get_ports {LED_TX_RED[0]}]
set_property PACKAGE_PIN AD26 [get_ports {LED_TX_RED[1]}]
set_property PACKAGE_PIN G26  [get_ports {LED_RX_GRN[0]}]
set_property PACKAGE_PIN AD25 [get_ports {LED_RX_GRN[1]}]
set_property PACKAGE_PIN D8   [get_ports LED_FPGA_CONFIG_GRN]

set_property PACKAGE_PIN L25  [get_ports ANT_PWR_EN]
set_property PACKAGE_PIN R20  [get_ports {RX_SW_CTRL[0]}]
set_property PACKAGE_PIN D14  [get_ports {RX_SW_CTRL[1]}]
set_property PACKAGE_PIN B14  [get_ports {ENABLE_TXRX_TDR[0]}]
set_property PACKAGE_PIN A14  [get_ports {ENABLE_TXRX_TDR[1]}]

set_property PACKAGE_PIN U17  [get_ports DAC_CS_N]
set_property PACKAGE_PIN R17  [get_ports DAC_MOSI]
set_property PACKAGE_PIN T17  [get_ports DAC_SCLK]
set_property PACKAGE_PIN R16  [get_ports DAC_CLR_N]

set_property PACKAGE_PIN R18  [get_ports MISC_I2C_SCL]
set_property PACKAGE_PIN T19  [get_ports MISC_I2C_SDA]

set_property PACKAGE_PIN K16  [get_ports TBOLT_SCL]
set_property PACKAGE_PIN K15  [get_ports TBOLT_SDA]
set_property PACKAGE_PIN C14  [get_ports {TBOLT_RIDGE_RESET_N}]
set_property PACKAGE_PIN G16  [get_ports {TBOLT_PD_CTRL_RESET}]

set_property PACKAGE_PIN K26  [get_ports NSYNC_GPIO0]
set_property PACKAGE_PIN P25  [get_ports NSYNC_PDN]
set_property PACKAGE_PIN M25  [get_ports {NSYNC_STATUS[0]}]
set_property PACKAGE_PIN P21  [get_ports {NSYNC_STATUS[1]}]

set_property PACKAGE_PIN A8   [get_ports {EXT_PPS_IN}]
set_property PACKAGE_PIN G9   [get_ports {PPS_OUT[0]}]
set_property PACKAGE_PIN G10  [get_ports {PPS_OUT[1]}]
set_property PACKAGE_PIN H8   [get_ports {PPS_OUT[2]}]
set_property PACKAGE_PIN H9   [get_ports {PPS_OUT[3]}]

set_property PACKAGE_PIN U16  [get_ports REF_CLK_SEL]
set_property PACKAGE_PIN P24  [get_ports TCXO_EN_N]

set_property PACKAGE_PIN F8   [get_ports AUTH_SDA]

# JESD204B
set_property PACKAGE_PIN P1   [get_ports {JESD_TX_N[0]}]
set_property PACKAGE_PIN P2   [get_ports {JESD_TX_P[0]}]
set_property PACKAGE_PIN M1   [get_ports {JESD_TX_N[1]}]
set_property PACKAGE_PIN M2   [get_ports {JESD_TX_P[1]}]

set_property PACKAGE_PIN R3   [get_ports {JESD_RX_N[0]}]
set_property PACKAGE_PIN R4   [get_ports {JESD_RX_P[0]}]
set_property PACKAGE_PIN N3   [get_ports {JESD_RX_N[1]}]
set_property PACKAGE_PIN N4   [get_ports {JESD_RX_P[1]}]

# These pins are routed, but unused
# set_property PACKAGE_PIN K1   [get_ports {JESD_TX_N[2]}]
# set_property PACKAGE_PIN K2   [get_ports {JESD_TX_P[2]}]
# set_property PACKAGE_PIN H1   [get_ports {JESD_TX_N[3]}]
# set_property PACKAGE_PIN H2   [get_ports {JESD_TX_P[3]}]
# set_property PACKAGE_PIN L3   [get_ports {JESD_RX_N[2]}]
# set_property PACKAGE_PIN L4   [get_ports {JESD_RX_P[2]}]
# set_property PACKAGE_PIN J3   [get_ports {JESD_RX_N[3]}]
# set_property PACKAGE_PIN J4   [get_ports {JESD_RX_P[3]}]


######################################################################################
# Pin Drive information
######################################################################################
#Defaulted drives to 8mA slow, may change driver strength from there as starting point

set_property IOSTANDARD LVDS           [get_ports {DEVCLK_*}]
set_property DIFF_TERM TRUE            [get_ports {DEVCLK_*}]
set_property IOSTANDARD LVDS           [get_ports {FPGA_REFCLK_*}]
set_property DIFF_TERM TRUE            [get_ports {FPGA_REFCLK_*}]
set_property IOSTANDARD LVDS           [get_ports {EXT_REFCLK_*}]
set_property DIFF_TERM TRUE            [get_ports {EXT_REFCLK_*}]
set_property IOSTANDARD LVDS           [get_ports {SYSREF_*}]
set_property DIFF_TERM TRUE            [get_ports {SYSREF_*}]

set_property IOSTANDARD LVCMOS33 [get_ports PCIE_PRESENT_N]
set_property IOSTANDARD LVCMOS18 [get_ports PCIE_RESET_N]

set_property IOSTANDARD LVCMOS18       [get_ports PG_1V2]
set_property IOSTANDARD LVCMOS18       [get_ports TYPEC_PWR_NEGOTIATED]
set_property IOSTANDARD LVCMOS18       [get_ports VBUS_ALERT_N]
set_property IOSTANDARD LVCMOS33       [get_ports GT_25W_PWR_SRC]

set_property IOSTANDARD LVCMOS18       [get_ports {ADRV_GPINT[0]}]
set_property DRIVE      8              [get_ports {ADRV_GPINT[0]}]
set_property SLEW       SLOW           [get_ports {ADRV_GPINT[0]}]
set_property IOSTANDARD LVCMOS18       [get_ports {ADRV_GPINT[1]}]
set_property DRIVE      8              [get_ports {ADRV_GPINT[1]}]
set_property SLEW       SLOW           [get_ports {ADRV_GPINT[1]}]
set_property IOSTANDARD LVCMOS18       [get_ports {ADRV_GPIO[0]}]
set_property DRIVE      8              [get_ports {ADRV_GPIO[0]}]
set_property SLEW       SLOW           [get_ports {ADRV_GPIO[0]}]
set_property IOSTANDARD LVCMOS18       [get_ports {ADRV_GPIO[1]}]
set_property DRIVE      8              [get_ports {ADRV_GPIO[1]}]
set_property SLEW       SLOW           [get_ports {ADRV_GPIO[1]}]
set_property IOSTANDARD LVCMOS18       [get_ports {ADRV_GPIO[2]}]
set_property DRIVE      8              [get_ports {ADRV_GPIO[2]}]
set_property SLEW       SLOW           [get_ports {ADRV_GPIO[2]}]
set_property IOSTANDARD LVCMOS18       [get_ports {ADRV_GPIO[3]}]
set_property DRIVE      8              [get_ports {ADRV_GPIO[3]}]
set_property SLEW       SLOW           [get_ports {ADRV_GPIO[3]}]
set_property IOSTANDARD LVCMOS18       [get_ports {ADRV_GPIO[4]}]
set_property DRIVE      8              [get_ports {ADRV_GPIO[4]}]
set_property SLEW       SLOW           [get_ports {ADRV_GPIO[4]}]
set_property IOSTANDARD LVCMOS18       [get_ports {ADRV_GPIO[5]}]
set_property DRIVE      8              [get_ports {ADRV_GPIO[5]}]
set_property SLEW       SLOW           [get_ports {ADRV_GPIO[5]}]
set_property IOSTANDARD LVCMOS18       [get_ports {ADRV_GPIO[6]}]
set_property DRIVE      8              [get_ports {ADRV_GPIO[6]}]
set_property SLEW       SLOW           [get_ports {ADRV_GPIO[6]}]
set_property IOSTANDARD LVCMOS18       [get_ports {ADRV_GPIO[7]}]
set_property DRIVE      8              [get_ports {ADRV_GPIO[7]}]
set_property SLEW       SLOW           [get_ports {ADRV_GPIO[7]}]
set_property IOSTANDARD LVCMOS18       [get_ports ADRV_SPI_DIO]
set_property DRIVE      8              [get_ports ADRV_SPI_DIO]
set_property SLEW       SLOW           [get_ports ADRV_SPI_DIO]
set_property IOSTANDARD LVDS           [get_ports {ADRV_SYNCOUT_*}]
set_property DIFF_TERM TRUE            [get_ports {ADRV_SYNCOUT_*}]
set_property IOSTANDARD LVCMOS18       [get_ports ADRV_ORXA_CTRL]
set_property DRIVE      8              [get_ports ADRV_ORXA_CTRL]
set_property SLEW       SLOW           [get_ports ADRV_ORXA_CTRL]
set_property IOSTANDARD LVCMOS18       [get_ports ADRV_ORXB_CTRL]
set_property DRIVE      8              [get_ports ADRV_ORXB_CTRL]
set_property SLEW       SLOW           [get_ports ADRV_ORXB_CTRL]
set_property IOSTANDARD LVCMOS18       [get_ports ADRV_RESET_N]
set_property DRIVE      8              [get_ports ADRV_RESET_N]
set_property SLEW       SLOW           [get_ports ADRV_RESET_N]
set_property IOSTANDARD LVCMOS18       [get_ports ADRV_SPI_CLK]
set_property DRIVE      8              [get_ports ADRV_SPI_CLK]
set_property SLEW       SLOW           [get_ports ADRV_SPI_CLK]
set_property IOSTANDARD LVCMOS18       [get_ports ADRV_SPI_DO]
set_property IOSTANDARD LVCMOS18       [get_ports ADRV_SPI_EN_N]
set_property DRIVE      8              [get_ports ADRV_SPI_EN_N]
set_property SLEW       SLOW           [get_ports ADRV_SPI_EN_N]
set_property IOSTANDARD LVDS           [get_ports {ADRV_SYNCIN_*}]
set_property DIFF_TERM TRUE            [get_ports {ADRV_SYNCIN_*}]
set_property IOSTANDARD LVCMOS18       [get_ports ADRV_TEST_EN]
set_property DRIVE      8              [get_ports ADRV_TEST_EN]
set_property SLEW       SLOW           [get_ports ADRV_TEST_EN]
set_property IOSTANDARD LVCMOS18       [get_ports ADRV_TRXA_CTRL]
set_property DRIVE      8              [get_ports ADRV_TRXA_CTRL]
set_property SLEW       SLOW           [get_ports ADRV_TRXA_CTRL]
set_property IOSTANDARD LVCMOS18       [get_ports ADRV_TRXB_CTRL]
set_property DRIVE      8              [get_ports ADRV_TRXB_CTRL]
set_property SLEW       SLOW           [get_ports ADRV_TRXB_CTRL]
set_property IOSTANDARD LVCMOS18       [get_ports ADRV_TRXC_CTRL]
set_property DRIVE      8              [get_ports ADRV_TRXC_CTRL]
set_property SLEW       SLOW           [get_ports ADRV_TRXC_CTRL]
set_property IOSTANDARD LVCMOS18       [get_ports ADRV_TRXD_CTRL]
set_property DRIVE      8              [get_ports ADRV_TRXD_CTRL]
set_property SLEW       SLOW           [get_ports ADRV_TRXD_CTRL]
set_property IOSTANDARD LVCMOS18       [get_ports ADRV_TRXE_CTRL]
set_property DRIVE      8              [get_ports ADRV_TRXE_CTRL]
set_property SLEW       SLOW           [get_ports ADRV_TRXE_CTRL]
set_property IOSTANDARD LVCMOS18       [get_ports ADRV_TRXF_CTRL]
set_property DRIVE      8              [get_ports ADRV_TRXF_CTRL]
set_property SLEW       SLOW           [get_ports ADRV_TRXF_CTRL]
set_property IOSTANDARD LVCMOS18       [get_ports ADRV_TRXG_CTRL]
set_property DRIVE      8              [get_ports ADRV_TRXG_CTRL]
set_property SLEW       SLOW           [get_ports ADRV_TRXG_CTRL]
set_property IOSTANDARD LVCMOS18       [get_ports ADRV_TRXH_CTRL]
set_property DRIVE      8              [get_ports ADRV_TRXH_CTRL]
set_property SLEW       SLOW           [get_ports ADRV_TRXH_CTRL]

set_property IOSTANDARD LVCMOS18       [get_ports JTAG_CPLD_TCK]
set_property DRIVE      8              [get_ports JTAG_CPLD_TCK]
set_property SLEW       SLOW           [get_ports JTAG_CPLD_TCK]
set_property IOSTANDARD LVCMOS18       [get_ports JTAG_CPLD_TDI]
set_property DRIVE      8              [get_ports JTAG_CPLD_TDI]
set_property SLEW       SLOW           [get_ports JTAG_CPLD_TDI]
set_property IOSTANDARD LVCMOS18       [get_ports JTAG_CPLD_TMS]
set_property DRIVE      8              [get_ports JTAG_CPLD_TMS]
set_property SLEW       SLOW           [get_ports JTAG_CPLD_TMS]
set_property IOSTANDARD LVCMOS18       [get_ports JTAG_TBOLT_TCK]
set_property DRIVE      8              [get_ports JTAG_TBOLT_TCK]
set_property SLEW       SLOW           [get_ports JTAG_TBOLT_TCK]
set_property IOSTANDARD LVCMOS18       [get_ports JTAG_TBOLT_TDI]
set_property DRIVE      8              [get_ports JTAG_TBOLT_TDI]
set_property SLEW       SLOW           [get_ports JTAG_TBOLT_TDI]
set_property IOSTANDARD LVCMOS18       [get_ports JTAG_TBOLT_TMS]
set_property DRIVE      8              [get_ports JTAG_TBOLT_TMS]
set_property SLEW       SLOW           [get_ports JTAG_TBOLT_TMS]
set_property IOSTANDARD LVCMOS18       [get_ports JTAG_CPLD_TDO]
set_property IOSTANDARD LVCMOS18       [get_ports JTAG_TBOLT_TDO]

set_property IOSTANDARD LVCMOS33       [get_ports LMK053_MISO]
set_property DRIVE      8              [get_ports LMK053_MISO]
set_property SLEW       SLOW           [get_ports LMK053_MISO]
set_property IOSTANDARD LVCMOS33       [get_ports LMK053_MOSI]
set_property DRIVE      8              [get_ports LMK053_MOSI]
set_property SLEW       SLOW           [get_ports LMK053_MOSI]
set_property IOSTANDARD LVCMOS33       [get_ports LMK32_MISO]
set_property IOSTANDARD LVCMOS33       [get_ports LMK32_STATUS]
set_property IOSTANDARD LVCMOS33       [get_ports LMK32_CS_N]
set_property DRIVE      8              [get_ports LMK32_CS_N]
set_property SLEW       SLOW           [get_ports LMK32_CS_N]
set_property IOSTANDARD LVCMOS33       [get_ports LMK32_MOSI]
set_property DRIVE      8              [get_ports LMK32_MOSI]
set_property SLEW       SLOW           [get_ports LMK32_MOSI]
set_property IOSTANDARD LVCMOS33       [get_ports LMK32_RESET]
set_property DRIVE      8              [get_ports LMK32_RESET]
set_property SLEW       SLOW           [get_ports LMK32_RESET]
set_property IOSTANDARD LVCMOS33       [get_ports LMK32_SCLK]
set_property DRIVE      8              [get_ports LMK32_SCLK]
set_property SLEW       SLOW           [get_ports LMK32_SCLK]
set_property IOSTANDARD LVCMOS33       [get_ports LMK32_VCXO_SEL_122M88]
set_property DRIVE      8              [get_ports LMK32_VCXO_SEL_122M88]
set_property SLEW       SLOW           [get_ports LMK32_VCXO_SEL_122M88]
set_property IOSTANDARD LVCMOS33       [get_ports LMK053_CS_N]
set_property DRIVE      8              [get_ports LMK053_CS_N]
set_property SLEW       SLOW           [get_ports LMK053_CS_N]
set_property IOSTANDARD LVCMOS33       [get_ports LMK053_SCLK]
set_property DRIVE      8              [get_ports LMK053_SCLK]
set_property SLEW       SLOW           [get_ports LMK053_SCLK]
set_property IOSTANDARD LVCMOS18       [get_ports LMK_SYNC_REVA]
set_property DRIVE      16             [get_ports LMK_SYNC_REVA]
set_property SLEW       FAST           [get_ports LMK_SYNC_REVA]
set_property IOSTANDARD LVCMOS33       [get_ports LMK_SYNC]
set_property DRIVE      16             [get_ports LMK_SYNC]
set_property SLEW       FAST           [get_ports LMK_SYNC]

set_property IOSTANDARD LVCMOS33       [get_ports GPS_PPS_OUT]
set_property IOSTANDARD LVCMOS33       [get_ports GPS_PWR_FAULT_N]
set_property IOSTANDARD LVCMOS18       [get_ports {GPS_REF[0]}]
set_property IOSTANDARD LVCMOS18       [get_ports {GPS_REF[1]}]
set_property IOSTANDARD LVCMOS33       [get_ports GPS_UART_TOFPGA]
set_property IOSTANDARD LVCMOS33       [get_ports GPS_REFSEL]
set_property DRIVE      8              [get_ports GPS_REFSEL]
set_property SLEW       SLOW           [get_ports GPS_REFSEL]
set_property IOSTANDARD LVCMOS33       [get_ports GPS_RESET_N]
set_property DRIVE      8              [get_ports GPS_RESET_N]
set_property SLEW       SLOW           [get_ports GPS_RESET_N]
set_property IOSTANDARD LVDS           [get_ports {GPS_SECREF_*}]
set_property IOSTANDARD LVCMOS33       [get_ports GPS_EXTINT]
set_property DRIVE      8              [get_ports GPS_EXTINT]
set_property SLEW       SLOW           [get_ports GPS_EXTINT]
set_property IOSTANDARD LVCMOS33       [get_ports GPS_UART_TOGPS]
set_property DRIVE      8              [get_ports GPS_UART_TOGPS]
set_property SLEW       SLOW           [get_ports GPS_UART_TOGPS]

set_property IOSTANDARD LVCMOS18       [get_ports CPLD_TX_CLK]
set_property IOSTANDARD LVCMOS18       [get_ports CPLD_TX_CLKEN]
set_property IOSTANDARD LVCMOS18       [get_ports {CPLD_TX_DATA[0]}]
set_property IOSTANDARD LVCMOS18       [get_ports {CPLD_TX_DATA[1]}]
set_property IOSTANDARD LVCMOS18       [get_ports {CPLD_TX_DATA[2]}]
set_property IOSTANDARD LVCMOS18       [get_ports {CPLD_TX_DATA[3]}]
set_property IOSTANDARD LVCMOS18       [get_ports {CPLD_TX_DATA[4]}]
set_property IOSTANDARD LVCMOS18       [get_ports {CPLD_TX_DATA[5]}]
set_property IOSTANDARD LVCMOS18       [get_ports {CPLD_TX_DATA[6]}]
set_property IOSTANDARD LVCMOS18       [get_ports {CPLD_TX_DATA[7]}]
set_property IOSTANDARD LVCMOS18       [get_ports CPLD_EXT_RST_R_N]
set_property DRIVE      8              [get_ports CPLD_EXT_RST_R_N]
set_property SLEW       FAST           [get_ports CPLD_EXT_RST_R_N]
set_property IOSTANDARD LVCMOS18       [get_ports CPLD_OSC_EN]
set_property DRIVE      4              [get_ports CPLD_OSC_EN]
set_property SLEW       SLOW           [get_ports CPLD_OSC_EN]
set_property IOSTANDARD LVCMOS18       [get_ports CPLD_RX_CLK]
set_property DRIVE      8              [get_ports CPLD_RX_CLK]
set_property SLEW       FAST           [get_ports CPLD_RX_CLK]
set_property IOSTANDARD LVCMOS18       [get_ports CPLD_RX_CLKEN]
set_property DRIVE      8              [get_ports CPLD_RX_CLKEN]
set_property SLEW       FAST           [get_ports CPLD_RX_CLKEN]
set_property IOSTANDARD LVCMOS18       [get_ports {CPLD_RX_DATA[0]}]
set_property DRIVE      8              [get_ports {CPLD_RX_DATA[0]}]
set_property SLEW       FAST           [get_ports {CPLD_RX_DATA[0]}]
set_property IOSTANDARD LVCMOS18       [get_ports {CPLD_RX_DATA[1]}]
set_property DRIVE      8              [get_ports {CPLD_RX_DATA[1]}]
set_property SLEW       FAST           [get_ports {CPLD_RX_DATA[1]}]
set_property IOSTANDARD LVCMOS18       [get_ports {CPLD_RX_DATA[2]}]
set_property DRIVE      8              [get_ports {CPLD_RX_DATA[2]}]
set_property SLEW       FAST           [get_ports {CPLD_RX_DATA[2]}]
set_property IOSTANDARD LVCMOS18       [get_ports {CPLD_RX_DATA[3]}]
set_property DRIVE      8              [get_ports {CPLD_RX_DATA[3]}]
set_property SLEW       FAST           [get_ports {CPLD_RX_DATA[3]}]
set_property IOSTANDARD LVCMOS18       [get_ports {CPLD_RX_DATA[4]}]
set_property DRIVE      8              [get_ports {CPLD_RX_DATA[4]}]
set_property SLEW       FAST           [get_ports {CPLD_RX_DATA[4]}]
set_property IOSTANDARD LVCMOS18       [get_ports {CPLD_RX_DATA[5]}]
set_property DRIVE      8              [get_ports {CPLD_RX_DATA[5]}]
set_property SLEW       FAST           [get_ports {CPLD_RX_DATA[5]}]
set_property IOSTANDARD LVCMOS18       [get_ports {CPLD_RX_DATA[6]}]
set_property DRIVE      8              [get_ports {CPLD_RX_DATA[6]}]
set_property SLEW       FAST           [get_ports {CPLD_RX_DATA[6]}]
set_property IOSTANDARD LVCMOS18       [get_ports {CPLD_RX_DATA[7]}]
set_property DRIVE      8              [get_ports {CPLD_RX_DATA[7]}]
set_property SLEW       FAST           [get_ports {CPLD_RX_DATA[7]}]
set_property IOSTANDARD LVCMOS18       [get_ports PCIE_RESET_N_TO_CPLD]
set_property DRIVE      8              [get_ports PCIE_RESET_N_TO_CPLD]
set_property SLEW       SLOW           [get_ports PCIE_RESET_N_TO_CPLD]

set_property IOSTANDARD LVCMOS33       [get_ports {FP_GPIO[0]}]
set_property DRIVE      8              [get_ports {FP_GPIO[0]}]
set_property SLEW       SLOW           [get_ports {FP_GPIO[0]}]
set_property IOSTANDARD LVCMOS33       [get_ports {FP_GPIO[1]}]
set_property DRIVE      8              [get_ports {FP_GPIO[1]}]
set_property SLEW       SLOW           [get_ports {FP_GPIO[1]}]
set_property IOSTANDARD LVCMOS33       [get_ports {FP_GPIO[2]}]
set_property DRIVE      8              [get_ports {FP_GPIO[2]}]
set_property SLEW       SLOW           [get_ports {FP_GPIO[2]}]
set_property IOSTANDARD LVCMOS33       [get_ports {FP_GPIO[3]}]
set_property DRIVE      8              [get_ports {FP_GPIO[3]}]
set_property SLEW       SLOW           [get_ports {FP_GPIO[3]}]
set_property IOSTANDARD LVCMOS33       [get_ports {FP_GPIO[4]}]
set_property DRIVE      8              [get_ports {FP_GPIO[4]}]
set_property SLEW       SLOW           [get_ports {FP_GPIO[4]}]
set_property IOSTANDARD LVCMOS33       [get_ports {FP_GPIO[5]}]
set_property DRIVE      8              [get_ports {FP_GPIO[5]}]
set_property SLEW       SLOW           [get_ports {FP_GPIO[5]}]
set_property IOSTANDARD LVCMOS33       [get_ports {FP_GPIO[6]}]
set_property DRIVE      8              [get_ports {FP_GPIO[6]}]
set_property SLEW       SLOW           [get_ports {FP_GPIO[6]}]
set_property IOSTANDARD LVCMOS33       [get_ports {FP_GPIO[7]}]
set_property DRIVE      8              [get_ports {FP_GPIO[7]}]
set_property SLEW       SLOW           [get_ports {FP_GPIO[7]}]
set_property IOSTANDARD LVCMOS33       [get_ports {FP_GPIO[8]}]
set_property DRIVE      8              [get_ports {FP_GPIO[8]}]
set_property SLEW       SLOW           [get_ports {FP_GPIO[8]}]
set_property IOSTANDARD LVCMOS33       [get_ports {FP_GPIO[9]}]
set_property DRIVE      8              [get_ports {FP_GPIO[9]}]
set_property SLEW       SLOW           [get_ports {FP_GPIO[9]}]

set_property IOSTANDARD LVCMOS18       [get_ports LED_CLK_STS_GRN]
set_property DRIVE      4              [get_ports LED_CLK_STS_GRN]
set_property SLEW       SLOW           [get_ports LED_CLK_STS_GRN]
set_property IOSTANDARD LVCMOS18       [get_ports LED_PWR_STS_BLUE]
set_property DRIVE      4              [get_ports LED_PWR_STS_BLUE]
set_property SLEW       SLOW           [get_ports LED_PWR_STS_BLUE]
set_property IOSTANDARD LVCMOS18       [get_ports LED_PWR_STS_ORANGE]
set_property DRIVE      4              [get_ports LED_PWR_STS_ORANGE]
set_property SLEW       SLOW           [get_ports LED_PWR_STS_ORANGE]
set_property IOSTANDARD LVCMOS18       [get_ports {LED_TX_GRN[0]}]
set_property DRIVE      4              [get_ports {LED_TX_GRN[0]}]
set_property SLEW       SLOW           [get_ports {LED_TX_GRN[0]}]
set_property IOSTANDARD LVCMOS18       [get_ports {LED_TX_GRN[1]}]
set_property DRIVE      4              [get_ports {LED_TX_GRN[1]}]
set_property SLEW       SLOW           [get_ports {LED_TX_GRN[1]}]
set_property IOSTANDARD LVCMOS18       [get_ports {LED_TX_RED[0]}]
set_property DRIVE      4              [get_ports {LED_TX_RED[0]}]
set_property SLEW       SLOW           [get_ports {LED_TX_RED[0]}]
set_property IOSTANDARD LVCMOS18       [get_ports {LED_TX_RED[1]}]
set_property DRIVE      4              [get_ports {LED_TX_RED[1]}]
set_property SLEW       SLOW           [get_ports {LED_TX_RED[1]}]
set_property IOSTANDARD LVCMOS18       [get_ports {LED_RX_GRN[0]}]
set_property DRIVE      4              [get_ports {LED_RX_GRN[0]}]
set_property SLEW       SLOW           [get_ports {LED_RX_GRN[0]}]
set_property IOSTANDARD LVCMOS18       [get_ports {LED_RX_GRN[1]}]
set_property DRIVE      4              [get_ports {LED_RX_GRN[1]}]
set_property SLEW       SLOW           [get_ports {LED_RX_GRN[1]}]
set_property IOSTANDARD LVCMOS33       [get_ports LED_FPGA_CONFIG_GRN]
set_property DRIVE      8              [get_ports LED_FPGA_CONFIG_GRN]
set_property SLEW       SLOW           [get_ports LED_FPGA_CONFIG_GRN]

set_property IOSTANDARD LVCMOS33       [get_ports ANT_PWR_EN]
set_property DRIVE      4              [get_ports ANT_PWR_EN]
set_property SLEW       SLOW           [get_ports ANT_PWR_EN]
set_property IOSTANDARD LVCMOS33       [get_ports {RX_SW_CTRL[0]}]
set_property DRIVE      8              [get_ports {RX_SW_CTRL[0]}]
set_property SLEW       SLOW           [get_ports {RX_SW_CTRL[0]}]
set_property IOSTANDARD LVCMOS33       [get_ports {RX_SW_CTRL[1]}]
set_property DRIVE      8              [get_ports {RX_SW_CTRL[1]}]
set_property SLEW       SLOW           [get_ports {RX_SW_CTRL[1]}]
set_property IOSTANDARD LVCMOS33       [get_ports {ENABLE_TXRX_TDR[0]}]
set_property DRIVE      8              [get_ports {ENABLE_TXRX_TDR[0]}]
set_property SLEW       SLOW           [get_ports {ENABLE_TXRX_TDR[0]}]
set_property IOSTANDARD LVCMOS33       [get_ports {ENABLE_TXRX_TDR[1]}]
set_property DRIVE      8              [get_ports {ENABLE_TXRX_TDR[1]}]
set_property SLEW       SLOW           [get_ports {ENABLE_TXRX_TDR[1]}]

set_property IOSTANDARD LVCMOS33       [get_ports DAC_CS_N]
set_property DRIVE      8              [get_ports DAC_CS_N]
set_property SLEW       SLOW           [get_ports DAC_CS_N]
set_property IOSTANDARD LVCMOS33       [get_ports DAC_MOSI]
set_property DRIVE      8              [get_ports DAC_MOSI]
set_property SLEW       SLOW           [get_ports DAC_MOSI]
set_property IOSTANDARD LVCMOS33       [get_ports DAC_SCLK]
set_property DRIVE      8              [get_ports DAC_SCLK]
set_property SLEW       SLOW           [get_ports DAC_SCLK]
set_property IOSTANDARD LVCMOS33       [get_ports DAC_CLR_N]
set_property DRIVE      8              [get_ports DAC_CLR_N]
set_property SLEW       SLOW           [get_ports DAC_CLR_N]

set_property IOSTANDARD LVCMOS33       [get_ports MISC_I2C_SCL]
set_property DRIVE      8              [get_ports MISC_I2C_SCL]
set_property SLEW       SLOW           [get_ports MISC_I2C_SCL]
set_property IOSTANDARD LVCMOS33       [get_ports MISC_I2C_SDA]
set_property DRIVE      8              [get_ports MISC_I2C_SDA]
set_property SLEW       SLOW           [get_ports MISC_I2C_SDA]

set_property IOSTANDARD LVCMOS18       [get_ports TBOLT_SCL]
set_property DRIVE      8              [get_ports TBOLT_SCL]
set_property SLEW       SLOW           [get_ports TBOLT_SCL]
set_property IOSTANDARD LVCMOS18       [get_ports TBOLT_SDA]
set_property DRIVE      8              [get_ports TBOLT_SDA]
set_property SLEW       SLOW           [get_ports TBOLT_SDA]
set_property IOSTANDARD LVCMOS33       [get_ports {TBOLT_RIDGE_RESET_N}]
set_property DRIVE      8              [get_ports {TBOLT_RIDGE_RESET_N}]
set_property SLEW       SLOW           [get_ports {TBOLT_RIDGE_RESET_N}]
set_property IOSTANDARD LVCMOS18       [get_ports {TBOLT_PD_CTRL_RESET}]
set_property DRIVE      8              [get_ports {TBOLT_PD_CTRL_RESET}]
set_property SLEW       SLOW           [get_ports {TBOLT_PD_CTRL_RESET}]

set_property IOSTANDARD LVCMOS33       [get_ports NSYNC_GPIO0]
set_property DRIVE      8              [get_ports NSYNC_GPIO0]
set_property SLEW       SLOW           [get_ports NSYNC_GPIO0]
set_property IOSTANDARD LVCMOS33       [get_ports NSYNC_PDN]
set_property SLEW       SLOW           [get_ports NSYNC_PDN]
set_property IOSTANDARD LVCMOS33       [get_ports {NSYNC_STATUS[0]}]
set_property IOSTANDARD LVCMOS33       [get_ports {NSYNC_STATUS[1]}]

set_property IOSTANDARD PCI33_3        [get_ports EXT_PPS_IN]
set_property IOSTANDARD LVCMOS33       [get_ports {PPS_OUT[0]}]
set_property DRIVE      16             [get_ports {PPS_OUT[0]}]
set_property SLEW       FAST           [get_ports {PPS_OUT[0]}]
set_property IOSTANDARD LVCMOS33       [get_ports {PPS_OUT[1]}]
set_property DRIVE      16             [get_ports {PPS_OUT[1]}]
set_property SLEW       FAST           [get_ports {PPS_OUT[1]}]
set_property IOSTANDARD LVCMOS33       [get_ports {PPS_OUT[2]}]
set_property DRIVE      16             [get_ports {PPS_OUT[2]}]
set_property SLEW       FAST           [get_ports {PPS_OUT[2]}]
set_property IOSTANDARD LVCMOS33       [get_ports {PPS_OUT[3]}]
set_property DRIVE      16             [get_ports {PPS_OUT[3]}]
set_property SLEW       FAST           [get_ports {PPS_OUT[3]}]

set_property IOSTANDARD LVCMOS33       [get_ports REF_CLK_SEL]
set_property DRIVE      8              [get_ports REF_CLK_SEL]
set_property SLEW       SLOW           [get_ports REF_CLK_SEL]
set_property IOSTANDARD LVCMOS33       [get_ports TCXO_EN_N]
set_property DRIVE      4              [get_ports TCXO_EN_N]
set_property SLEW       SLOW           [get_ports TCXO_EN_N]

set_property IOSTANDARD LVCMOS33       [get_ports AUTH_SDA]
set_property DRIVE      4              [get_ports AUTH_SDA]
set_property SLEW       SLOW           [get_ports AUTH_SDA]

# DRAM internal VREF - (Required for SYSCLK)
set_property INTERNAL_VREF 0.75 [get_iobanks 33]

#-------------------------------------------------------------
# PCI Express Section. Most constraints here come from adapting a Xilinx generated
#  constraint.
#-------------------------------------------------------------

#--------------
# PCIe Reset pin IO Standard.
#
# Formerly these constraints were provided (copied from the Xilinx example project).
# Since the InChWORM really only cares about the reset input to the core (which may be
#  composed of the pin and other components) the actual PCIe reset pin constraints
#  are left to the user to select whatever polarity (pullup or pulldown) and IO standard
#  fit best the product design.

#--------------
# PCIe RefClock IBUFDS location
#
# Location of the IBUFDS cell that receives the PCIe reference clock. This is
# equivalent of constraining the location of each of the two clock pins (P and N)
#

set_property LOC IBUFDS_GTE2_X0Y3 [get_cells PcieRefClkIBufds]

#--------------
# PCIe Transceiver locations
#
# These constraints select the transceivers to be used,  which also dictates the pinout
#  for the transmit and receive differential pairs.
#
# To find a relation between GTXE2 channel, pins and MGT_Banks, see pages 390-394 of the
# following document:
#
# http://www.xilinx.com/support/documentation/user_guides/ug476_7Series_Transceivers.pdf

# PCIe Lane 0 (GTXE2_CHANNEL_X0Y7 uses pins AR2, AR1, AP8 and AP7)
set_property LOC GTXE2_CHANNEL_X0Y7 [get_cells {PcieIp/inst/inst/gt_top_i/pipe_wrapper_i/pipe_lane[0].gt_wrapper_i/gtx_channel.gtxe2_channel_i}]
# PCIe Lane 1 (GTXE2_CHANNEL_X0Y6 uses pins AT4, AT3, AR6 and AR5)
set_property LOC GTXE2_CHANNEL_X0Y6 [get_cells {PcieIp/inst/inst/gt_top_i/pipe_wrapper_i/pipe_lane[1].gt_wrapper_i/gtx_channel.gtxe2_channel_i}]
# PCIe Lane 2 (GTXE2_CHANNEL_X0Y5 uses pins AV8, AV7, AU4 and AU3)
set_property LOC GTXE2_CHANNEL_X0Y5 [get_cells {PcieIp/inst/inst/gt_top_i/pipe_wrapper_i/pipe_lane[2].gt_wrapper_i/gtx_channel.gtxe2_channel_i}]
# PCIe Lane 3 (GTXE2_CHANNEL_X0Y4 uses pins AY2, AY1, AX8 and AX7)
set_property LOC GTXE2_CHANNEL_X0Y4 [get_cells {PcieIp/inst/inst/gt_top_i/pipe_wrapper_i/pipe_lane[3].gt_wrapper_i/gtx_channel.gtxe2_channel_i}]

set_property PACKAGE_PIN B5 [get_ports {PCIE_RX_N[0]}]
set_property PACKAGE_PIN B6 [get_ports {PCIE_RX_P[0]}]
set_property PACKAGE_PIN A3 [get_ports {PCIE_TX_N[0]}]
set_property PACKAGE_PIN A4 [get_ports {PCIE_TX_P[0]}]
set_property PACKAGE_PIN C3 [get_ports {PCIE_RX_N[1]}]
set_property PACKAGE_PIN C4 [get_ports {PCIE_RX_P[1]}]
set_property PACKAGE_PIN B1 [get_ports {PCIE_TX_N[1]}]
set_property PACKAGE_PIN B2 [get_ports {PCIE_TX_P[1]}]
set_property PACKAGE_PIN E3 [get_ports {PCIE_RX_N[2]}]
set_property PACKAGE_PIN E4 [get_ports {PCIE_RX_P[2]}]
set_property PACKAGE_PIN D1 [get_ports {PCIE_TX_N[2]}]
set_property PACKAGE_PIN D2 [get_ports {PCIE_TX_P[2]}]
set_property PACKAGE_PIN G3 [get_ports {PCIE_RX_N[3]}]
set_property PACKAGE_PIN G4 [get_ports {PCIE_RX_P[3]}]
set_property PACKAGE_PIN F1 [get_ports {PCIE_TX_N[3]}]
set_property PACKAGE_PIN F2 [get_ports {PCIE_TX_P[3]}]


#--------------
# PCI Express Block location.
#  This constraint selects the PCI Express Block to be used.
#

set_property LOC PCIE_X0Y0 [get_cells {PcieIp/inst/inst/pcie_top_i/pcie_7x_i/pcie_block_i}]

#
# BlockRAM placement
#
set_property LOC RAMB36_X5Y35 [get_cells {inst/pcie_top_i/pcie_7x_i/pcie_bram_top/pcie_brams_rx/brams[3].ram/use_tdp.ramb36/genblk*.bram36_tdp_bl.bram36_tdp_bl}]
set_property LOC RAMB36_X4Y36 [get_cells {inst/pcie_top_i/pcie_7x_i/pcie_bram_top/pcie_brams_rx/brams[2].ram/use_tdp.ramb36/genblk*.bram36_tdp_bl.bram36_tdp_bl}]
set_property LOC RAMB36_X4Y35 [get_cells {inst/pcie_top_i/pcie_7x_i/pcie_bram_top/pcie_brams_rx/brams[1].ram/use_tdp.ramb36/genblk*.bram36_tdp_bl.bram36_tdp_bl}]
set_property LOC RAMB36_X4Y34 [get_cells {inst/pcie_top_i/pcie_7x_i/pcie_bram_top/pcie_brams_rx/brams[0].ram/use_tdp.ramb36/genblk*.bram36_tdp_bl.bram36_tdp_bl}]
set_property LOC RAMB36_X4Y33 [get_cells {inst/pcie_top_i/pcie_7x_i/pcie_bram_top/pcie_brams_tx/brams[0].ram/use_tdp.ramb36/genblk*.bram36_tdp_bl.bram36_tdp_bl}]
set_property LOC RAMB36_X4Y32 [get_cells {inst/pcie_top_i/pcie_7x_i/pcie_bram_top/pcie_brams_tx/brams[1].ram/use_tdp.ramb36/genblk*.bram36_tdp_bl.bram36_tdp_bl}]
set_property LOC RAMB36_X4Y31 [get_cells {inst/pcie_top_i/pcie_7x_i/pcie_bram_top/pcie_brams_tx/brams[2].ram/use_tdp.ramb36/genblk*.bram36_tdp_bl.bram36_tdp_bl}]
set_property LOC RAMB36_X4Y30 [get_cells {inst/pcie_top_i/pcie_7x_i/pcie_bram_top/pcie_brams_tx/brams[3].ram/use_tdp.ramb36/genblk*.bram36_tdp_bl.bram36_tdp_bl}]
