#
# Copyright 2010-2012 Ettus Research LLC
#

##################################################
# GPMC Sources
##################################################
GPMC_SRCS = $(abspath $(addprefix $(BASE_DIR)/../gpmc/, \
cross_clock_reader.v \
fifo_to_gpmc.v \
gpmc.v \
gpmc_to_fifo.v \
))
