# This job will execute the changeset_testlist.py script, which in turn will
# compute a list of tests that need to be executed.
# The script itself produces the correct output to set a variable for a future
# stage.

parameters:
- name: skip_analyze_changeset
  type: boolean
  default: false
- name: target_branch
  type: string
  default: "origin/master"

jobs:
  - job: analyze
    displayName: Analyze Changeset
    pool:
      name: Drivers-NIBuildFarm-RFMIBUILD
      demands: sh
    condition: not(${{ parameters.skip_analyze_changeset }})
    steps:
    - checkout: self
      clean: true
    - bash: |
        if [[ $AGENT_OS == "Windows_NT" ]]; then
            VENV_BIN_DIR="Scripts"
        else
            VENV_BIN_DIR="bin"
        fi
        python3 -m venv $AGENT_TEMPDIRECTORY/ac_venv
        $AGENT_TEMPDIRECTORY/ac_venv/$VENV_BIN_DIR/pip install --upgrade pip
        $AGENT_TEMPDIRECTORY/ac_venv/$VENV_BIN_DIR/pip install ruamel.yaml clang-format==14.0.6 ni-python-styleguide
        git branch
        set -o xtrace
        $AGENT_TEMPDIRECTORY/ac_venv/$VENV_BIN_DIR/python3 tools/changeset_testlist.py \
                --target-branch $TARGET_BRANCH \
                --set-azdo-var UhdTestList \
                --list-tests
      name: gen_testlist
      displayName: Generate Test-List
      env:
        TARGET_BRANCH: ${{ parameters.target_branch }}
    - bash: |
        if [[ $AGENT_OS == "Windows_NT" ]]; then
            VENV_BIN_DIR="Scripts"
        else
            VENV_BIN_DIR="bin"
        fi
        source $AGENT_TEMPDIRECTORY/ac_venv/$VENV_BIN_DIR/activate
        if [[ $GEN_TESTLIST_UHDTESTLIST =~ "clang-format" ]]; then
            $AGENT_TEMPDIRECTORY/ac_venv/$VENV_BIN_DIR/python3 \
                tools/run-clang-format.py . -r --patch-file clang-format.patch \
                    --clang-format-executable `which clang-format`
        fi
      name: run_clang_format
      displayName: Conditionally run clang-format

    - publish: clang-format.patch
      artifact: clang-format patch file
      displayName: Publish clang-format patch file
      condition: failed()

