parameters:
- name: uhdSrcDir
  type: string
- name: uhdArtifactSource
  default: current
  type: string
- name: uhdFpgaArtifactSource
  type: string
  default: current
- name: fpga_imgs_source
  type: string
- name: testDevices
  type: string
  default: 'n3xx'
- name: extra_rf_test_args
  type: string
  default: ''

jobs:
- template: job-uhd-rf-tests.yml
  parameters:
    toolset: 'make'
    uhdSrcDir: '${{ parameters.uhdSrcDir }}'
    uhdArtifactSource: '${{ parameters.uhdArtifactSource }}'
    uhdFpgaArtifactSource: '${{ parameters.uhdFpgaArtifactSource }}'
    fpga_imgs_source: '${{ parameters.fpga_imgs_source }}'
    redisHost: ''
    extra_rf_test_args: '${{ parameters.extra_rf_test_args }}'
    dutMatrix:
      ${{ if contains(parameters.testDevices, 'n3xx') }}:
        pebbles-n310-0:
          devType: 'n3xx'
          devModel: 'n310'
          devName: pebbles-n310-0
          devSerial: '$(n310_devSerial)'
          devHostname: 'ni-n3xx-$(n310_devSerial)'
          devBus: 'ip'
          devAddr: '192.168.40.17'
          sfpAddrs: '192.168.10.17,192.168.40.17'
          devFpga: 'HG'
          devtestPattern: 'n3x0'
          devSDImage: gnuradio-image-ni-sulfur-rev11-mender.sdimg.bz2
          devLabgridConfig: config/labgrid/pebbles-labgrid/device-configs/pebbles-n310-0.yml
          pytestDUT: 'n310-0'
          pytestAtsConfig: 'uhd_oss_ats'
          pipelineAgent: pebbles-agent-1
