parameters:
- name: uhdSrcDir
  type: string
- name: uhdArtifactSource
  type: string
  default: current
- name: uhdFpgaArtifactSource
  type: string
  default: current
- name: fpga_imgs_source
  type: string
- name: testDevices
  type: string
  default: 'x310'
- name: extra_rf_test_args
  type: string
  default: ''

jobs:
- template: job-uhd-rf-tests.yml
  parameters:
    toolset: 'make'
    uhdSrcDir: '${{ parameters.uhdSrcDir }}'
    uhdArtifactSource: '${{ parameters.uhdArtifactSource }}'
    uhdFpgaArtifactSource: ${{ parameters.uhdFpgaArtifactSource }}
    fpga_imgs_source: '${{ parameters.fpga_imgs_source }}'
    redisHost: 'sdr-osmium-test'
    vivado_dir: '/opt/Xilinx/Vivado_Lab/2023.2/'
    extra_rf_test_args: '${{ parameters.extra_rf_test_args }}'
    dutMatrix:
        x310-obx-0:
          devType: 'x300'
          devModel: 'x310'
          devName: x310-obx-0
          devSerial: '3138E8D'
          db0Serial: '34A3B9C'
          db1Serial: '34A3BA0'
          supportsCorrections: true
          devBus: 'ip'
          devAddr: '192.168.40.2'
          sfpAddrs: '192.168.40.2'
          devFpga: 'XG'
          devtestPattern: 'x300'
          pytestDUT: 'x310'
          pytestAtsConfig: 'osmium_ats'
          pipelineAgent: 'obx-ats-agent'
          jtagSerial: '251635138E8D'
          jtagServer: 'nitest@sdr-osmium-test'
