#
# Copyright 2021 Ettus Research, a National Instruments Brand
#
# SPDX-License-Identifier: LGPL-3.0-or-later
#

parameters:
- name: build_linux
  type: string
  default: Auto-detect
- name: build_mac
  type: string
  default: Auto-detect
- name: build_win
  type: string
  default: Auto-detect
- name: custom_boost_version
  type: boolean
  default: false
- name: custom_boost_version_url
  type: string
  default: 'https://boostorg.jfrog.io/artifactory/main/release/1.76.0/source/boost_1_76_0.tar.bz2'
- name: release_binaries
  type: boolean
  default: false
- name: testLength
  type: string
- name: run_streaming_tests
  type: string
  default: Auto-detect
- name: build_sdk
  type: boolean
  default: false
- name: cache_sstate
  type: boolean
  default: true
- name: build_e310_sg1
  type: boolean
  default: true
- name: build_e310_sg3
  type: boolean
  default: true
- name: build_e320
  type: boolean
  default: true
- name: build_n3xx
  type: boolean
  default: true
- name: build_x4xx
  type: boolean
  default: true
- name: fpga_imgs_base_url
  type: string
  displayName: FPGA Images Base URL
  default: 'Internal'
- name: skip_analyze_changeset
  type: boolean
  default: false

variables:
- template: ../uhd-pipeline-vars.yml

resources:
  pipelines:
  - pipeline: uhd_build_docker_container
    source: 'uhddev Build Docker Containers'
    branch: master
  - pipeline: usrp-kas-pipeline
    source: 'usrp-kas'
    branch: zeus-ci
  repositories:
  - repository: meta-ettus
    type: github
    name: EttusResearch/meta-ettus-dev
    endpoint: EttusResearch
    ref: zeus-ci
  - repository: gnuradio
    type: github
    name: gnuradio/gnuradio
    endpoint: EttusResearch
    ref: maint-3.8
  - repository: gr-ettus
    type: github
    name: EttusResearch/gr-ettusdev
    endpoint: EttusResearch
    ref: master
  - repository: ettus-rts
    type: github
    endpoint: EttusResearch
    name: EttusResearch/ettus-rts
    ref: master

stages:
  # This stage will analyze code that is being tested, and generate variables
  # that can be used to control conditional execution of future stages. Any
  # stage that shall run conditionally must therefore depend on this stage.
- stage: analyze_changeset
  displayName: Analyze Changeset
  dependsOn: []
  jobs:
  - template: job-analyze-changeset.yml
    parameters:
      skip_analyze_changeset: ${{ parameters.skip_analyze_changeset }}
- stage: build_uhd_stage_linux
  displayName: Build UHD Linux
  dependsOn: analyze_changeset
  # This will make $(UhdTestList) available to jobs/steps/tasks, but not for the
  # condition.
  variables:
    UhdTestList: $[stageDependencies.analyze_changeset.analyze.outputs['gen_testlist.UhdTestList']]
  # This stage is executed if any of these are true:
  # - build_linux is set to Force-yes
  # - build_linux is set to auto, and the UhdTestList contains UHD Linux builds
  condition: >
    and(succeeded(),
    or(
      eq('${{ parameters.build_linux }}', 'Force-yes'),
      and(
        eq('${{ parameters.build_linux }}', 'Auto-detect'),
        or(
          contains(dependencies.analyze_changeset.outputs['analyze.gen_testlist.UhdTestList'], 'uhd.build.linux'),
          contains(dependencies.analyze_changeset.outputs['analyze.gen_testlist.UhdTestList'], 'uhd.build.all')
        )
      )
    ))
  jobs:
  - template: job-get-latest-uhd-docker.yml
  - template: job-uhd-build-src.yml
    parameters:
      toolset: make
  - template: job-uhd-build-src.yml
    parameters:
      toolset: make_trace
  - template: job-uhd-build-src.yml
    parameters:
      toolset: ninja
  - ${{ if parameters.custom_boost_version }}:
    - template: job-uhd-build-src.yml
      parameters:
        toolset: make_custom_boost_version
        custom_boost_version_url: ${{ parameters.custom_boost_version_url }}

- stage: build_uhd_stage_win
  displayName: Build UHD Windows
  dependsOn: analyze_changeset
  condition: >
    and(succeeded(),
    or(
      eq('${{ parameters.build_win }}', 'Force-yes'),
      and(
        eq('${{ parameters.build_win }}', 'Auto-detect'),
        or(
          contains(dependencies.analyze_changeset.outputs['analyze.gen_testlist.UhdTestList'], 'uhd.build.windows'),
          contains(dependencies.analyze_changeset.outputs['analyze.gen_testlist.UhdTestList'], 'uhd.build.all')
        )
      )
    ))
  jobs:
  - template: job-get-latest-uhd-docker.yml
  - template: job-uhd-build-src.yml
    parameters:
      toolset: msbuild
      release_binaries: ${{ parameters.release_binaries }}
  - template: job-uhd-build-src.yml
    parameters:
      toolset: msbuild_python
      release_binaries: ${{ parameters.release_binaries }}

- stage: build_uhd_stage_mac
  displayName: Build UHD macOS
  dependsOn: analyze_changeset
  condition: >
    and(succeeded(),
    or(
      eq('${{ parameters.build_mac }}', 'Force-yes'),
      and(
        eq('${{ parameters.build_mac }}', 'Auto-detect'),
        or(
          contains(dependencies.analyze_changeset.outputs['analyze.gen_testlist.UhdTestList'], 'uhd.build.mac'),
          contains(dependencies.analyze_changeset.outputs['analyze.gen_testlist.UhdTestList'], 'uhd.build.all')
        )
      )
    ))
  jobs:
  - template: job-get-latest-uhd-docker.yml
  - template: job-uhd-build-src.yml
    parameters:
      toolset: make_homebrew_macos

- stage: build_uhd_embedded_system_images
  displayName: Build UHD Embedded System Images
  dependsOn: analyze_changeset
  # If skip_analyze_changeset is true (e.g., during a regular mono pipeline)
  # then we build depending on the checkboxes (e.g., build_x4xx). If
  # skip_analyze_changeset is false (e.g., during a PR mono pipeline) we AND
  # the checkboxes with their respective conditions. This can be improved: Right
  # now, if any embedded condition is true, then all embedded targets with a
  # checkbox will be built.
  condition: >
    and(
      succeeded(),
      or(
        and(
          ${{ parameters.skip_analyze_changeset }},
          or(
            ${{ parameters.build_e310_sg1 }},
            ${{ parameters.build_e310_sg3 }},
            ${{ parameters.build_e320 }},
            ${{ parameters.build_n3xx }},
            ${{ parameters.build_x4xx }}
          )
        ),
        or(
          contains(dependencies.analyze_changeset.outputs['analyze.gen_testlist.UhdTestList'], 'uhd.build.all'),
          contains(dependencies.analyze_changeset.outputs['analyze.gen_testlist.UhdTestList'], 'uhd.build.linux'),
          contains(dependencies.analyze_changeset.outputs['analyze.gen_testlist.UhdTestList'], 'mpm.build'),
          contains(dependencies.analyze_changeset.outputs['analyze.gen_testlist.UhdTestList'], 'hw.streaming.all'),
          contains(dependencies.analyze_changeset.outputs['analyze.gen_testlist.UhdTestList'], 'hw.streaming.e3'),
          contains(dependencies.analyze_changeset.outputs['analyze.gen_testlist.UhdTestList'], 'hw.streaming.n3'),
          contains(dependencies.analyze_changeset.outputs['analyze.gen_testlist.UhdTestList'], 'hw.streaming.x4'),
          contains(dependencies.analyze_changeset.outputs['analyze.gen_testlist.UhdTestList'], 'hw.rf.all'),
          contains(dependencies.analyze_changeset.outputs['analyze.gen_testlist.UhdTestList'], 'hw.rf.e3'),
          contains(dependencies.analyze_changeset.outputs['analyze.gen_testlist.UhdTestList'], 'hw.rf.n3'),
          contains(dependencies.analyze_changeset.outputs['analyze.gen_testlist.UhdTestList'], 'hw.rf.x4'),
          contains(dependencies.analyze_changeset.outputs['analyze.gen_testlist.UhdTestList'], 'devtest.all'),
          contains(dependencies.analyze_changeset.outputs['analyze.gen_testlist.UhdTestList'], 'devtest.e3'),
          contains(dependencies.analyze_changeset.outputs['analyze.gen_testlist.UhdTestList'], 'devtest.n3'),
          contains(dependencies.analyze_changeset.outputs['analyze.gen_testlist.UhdTestList'], 'devtest.x4')
        )
      )
    )
  variables:
    AUTO_CONF: $(Agent.BuildDirectory)/auto.conf
  jobs:
    - template: .ci/templates/job_build_filesystem.yml@meta-ettus
      parameters:
        build_sdk: ${{ parameters.build_sdk }}
        cache_sstate: ${{ parameters.cache_sstate }}
        cache_downloads: False
        machines:
          - ${{ if parameters.build_e310_sg1 }}:
            - e310_sg1
          - ${{ if parameters.build_e310_sg3 }}:
            - e310_sg3
          - ${{ if parameters.build_e320 }}:
            - e320
          - ${{ if parameters.build_n3xx }}:
            - n3xx
          - ${{ if parameters.build_x4xx }}:
            - x4xx
        auto_conf: $AUTO_CONF
        run_from_external_repo: true
        prebuild_steps:
        - script: |
            rm $(AUTO_CONF)
            touch $(AUTO_CONF)
          displayName: create auto.conf
        - template: .ci/templates/oe_localconf_externalsrc.yml@meta-ettus
          parameters:
            conf_file: $AUTO_CONF
            repository: self
            package_paths:
              - package: uhd
                path: host
              - package: mpmd
                path: mpm
        # If requested, we set a variable "UHD_BASE_URL", which is consumed by
        # the uhd-fpga-images recipe to an internal file server which is closer
        # to the build machines. It is simply appended to auto.conf, where
        # bitbake will pick it up and apply it to the recipe.
        - ${{ if contains(parameters.fpga_imgs_base_url, 'Internal') }}:
          - bash: |
              cat <<EOF >>$AUTO_CONF
              UHD_BASE_URL = "$FILE_SERVER_URL"
              EOF
            env:
              FILE_SERVER_URL: $(InternalFileServerUrl)
        postbuild_steps:
        - script: |
            rm $(AUTO_CONF)
          displayName: delete auto.conf
          condition: always()

- stage: package_uhd_src
  displayName: Package UHD Source
  dependsOn: analyze_changeset
  jobs:
  - template: job-get-latest-uhd-docker.yml
  - template: job-uhd-package-src.yml
    parameters:
      uhdSrcDir: $(Build.SourcesDirectory)
      uhdBuildDir: $(Build.BinariesDirectory)/uhddev/build
      release_binaries: ${{ parameters.release_binaries }}

- stage: build_gnuradio_stage_linux
  displayName: Build gnuradio Linux
  dependsOn:
  - build_uhd_stage_linux
  - analyze_changeset
  # Anytime we build UHD, we also rebuild GNU Radio to see if we broke compat.
  condition: >
    and(succeeded(),
    or(
      eq('${{ parameters.build_linux }}', 'Force-yes'),
      and(
        eq('${{ parameters.build_linux }}', 'Auto-detect'),
        or(
          contains(dependencies.analyze_changeset.outputs['analyze.gen_testlist.UhdTestList'], 'uhd.build.linux'),
          contains(dependencies.analyze_changeset.outputs['analyze.gen_testlist.UhdTestList'], 'uhd.build.all')
        )
      )
    ))
  jobs:
  - template: job-get-latest-uhd-docker.yml
  - template: job-gnuradio-grettus-build-src.yml
    parameters:
      toolset: make

- stage: build_uhd_installer_stage_ubuntu
  displayName: Build UHD Installers Ubuntu
  dependsOn: build_uhd_stage_linux
  jobs:
    - template: job-get-latest-uhd-docker.yml
    - template: job-uhd-build-installer.yml
      parameters:
        toolset: ubuntu_deb
        installer: deb

- stage: build_uhd_installer_stage_fedora
  displayName: Build UHD Installers Fedora
  dependsOn: build_uhd_stage_linux
  jobs:
    - template: job-get-latest-uhd-docker.yml
    - template: job-uhd-build-installer.yml
      parameters:
        toolset: fedora_rpm
        installer: rpm
        releaseBinaries: ${{ parameters.release_binaries }}

- stage: build_uhd_installer_stage_win
  displayName: Build UHD Installers Windows
  dependsOn: build_uhd_stage_win
  jobs:
    - template: job-get-latest-uhd-docker.yml
    - template: job-uhd-build-installer.yml
      parameters:
        toolset: msbuild
        installer: nsis
        releaseBinaries: ${{ parameters.release_binaries }}
        fpga_imgs_base_url: ${{ parameters.fpga_imgs_base_url }}
    - template: job-uhd-build-installer.yml
      parameters:
        toolset: msbuild_python
        installer: nsis
        fpga_imgs_base_url: ${{ parameters.fpga_imgs_base_url }}
    - ${{ if parameters.release_binaries }}:
      - template: job-uhd-build-installer-signing.yml
        parameters:
          toolset: msbuild
          installer: nsis

- stage: devtest_uhd_x3xx_b2xx_stage
  displayName: devtest UHD x3xx b2xx
  dependsOn:
  - build_uhd_stage_linux
  - analyze_changeset
  condition: >
    and(
      succeeded(),
      or(
        ${{ parameters.skip_analyze_changeset }},
        contains(dependencies.analyze_changeset.outputs['analyze.gen_testlist.UhdTestList'], 'devtest.all'),
        contains(dependencies.analyze_changeset.outputs['analyze.gen_testlist.UhdTestList'], 'devtest.b2'),
        contains(dependencies.analyze_changeset.outputs['analyze.gen_testlist.UhdTestList'], 'devtest.x3')
      )
    )
  jobs:
  - template: job-uhd-devtest-rhombus.yml
    parameters:
      testOS: ubuntu2004
      uhdSrcDir: $(Build.SourcesDirectory)
      testDevices: 'x3xx,b2xx'

- stage: devtest_uhd_n3xx_e320_stage
  displayName: devtest UHD n3xx e320
  dependsOn:
  - build_uhd_stage_linux
  - build_uhd_embedded_system_images
  - analyze_changeset
  condition: >
    and(
      succeeded(),
      or(
        ${{ parameters.skip_analyze_changeset }},
        contains(dependencies.analyze_changeset.outputs['analyze.gen_testlist.UhdTestList'], 'devtest.all'),
        contains(dependencies.analyze_changeset.outputs['analyze.gen_testlist.UhdTestList'], 'devtest.n3'),
        contains(dependencies.analyze_changeset.outputs['analyze.gen_testlist.UhdTestList'], 'devtest.e320')
      )
    )
  jobs:
  - template: job-uhd-devtest-rhombus.yml
    parameters:
      testOS: ubuntu2004
      uhdSrcDir: $(Build.SourcesDirectory)
      testDevices: 'n3xx,e320'

- stage: test_uhd_x4xx_stage
  displayName: Test UHD x4xx
  dependsOn:
  - build_uhd_stage_linux
  - build_uhd_embedded_system_images
  - build_gnuradio_stage_linux
  - analyze_changeset
  # This will make $(UhdTestList) available to jobs/steps/tasks, but not for the
  # condition.
  variables:
    UhdTestList: $[stageDependencies.analyze_changeset.analyze.outputs['gen_testlist.UhdTestList']]
  condition: >
    and(
      succeeded(),
      or(
        ${{ parameters.skip_analyze_changeset }},
        contains(dependencies.analyze_changeset.outputs['analyze.gen_testlist.UhdTestList'], 'hw.rf.all'),
        contains(dependencies.analyze_changeset.outputs['analyze.gen_testlist.UhdTestList'], 'hw.rf.x4xx'),
        contains(dependencies.analyze_changeset.outputs['analyze.gen_testlist.UhdTestList'], 'hw.rf.x410'),
        contains(dependencies.analyze_changeset.outputs['analyze.gen_testlist.UhdTestList'], 'hw.rf.x440'),
        contains(dependencies.analyze_changeset.outputs['analyze.gen_testlist.UhdTestList'], 'devtest.all'),
        contains(dependencies.analyze_changeset.outputs['analyze.gen_testlist.UhdTestList'], 'devtest.x410'),
        contains(dependencies.analyze_changeset.outputs['analyze.gen_testlist.UhdTestList'], 'devtest.x440')
    ))
  jobs:
  - template: tests/job-uhd-x410-hardware-tests-sdr-test0.yml
    parameters:
      testOS: ubuntu1804
  - template: tests/job-uhd-x440-hardware-tests-sdr-test0.yml
    parameters:
      testOS: ubuntu1804
  - template: tests/job-uhd-x410-hardware-tests-pebbles.yml
    parameters:
      testOS: ubuntu1804
  - template: tests/job-uhd-x440-hardware-tests-pebbles.yml
    parameters:
      testOS: ubuntu1804

- stage: test_uhd_rf_test_stage
  displayName: Run rf tests n3xx
  dependsOn:
  - analyze_changeset
  - build_uhd_stage_linux
  - build_uhd_embedded_system_images
  - build_gnuradio_stage_linux
  condition: >
    and(
      succeeded(),
      or(
        ${{ parameters.skip_analyze_changeset }},
        contains(dependencies.analyze_changeset.outputs['analyze.gen_testlist.UhdTestList'], 'hw.rf.all'),
        contains(dependencies.analyze_changeset.outputs['analyze.gen_testlist.UhdTestList'], 'hw.rf.n320'),
        contains(dependencies.analyze_changeset.outputs['analyze.gen_testlist.UhdTestList'], 'hw.rf.n310'),
        contains(dependencies.analyze_changeset.outputs['analyze.gen_testlist.UhdTestList'], 'hw.rf.n3xx')
    ))
  jobs:
  - template: job-uhd-rf-tests-pebbles.yml
    parameters:
      uhdSrcDir: $(Build.SourcesDirectory)/uhddev
      testOS: ubuntu1804
      testDevices: 'n3xx'

- stage: test_streaming_stage
  displayName: Test UHD Streaming
  dependsOn:
  - analyze_changeset
  - build_uhd_stage_linux
  - build_uhd_embedded_system_images
  condition: >
    and(
      succeeded('build_uhd_stage_linux'),
      succeeded('build_uhd_embedded_system_images'),
      ${{ parameters.run_streaming_tests }},
      or(
        ${{ parameters.skip_analyze_changeset }},
        contains(dependencies.analyze_changeset.outputs['analyze.gen_testlist.UhdTestList'], 'hw.streaming')
      )
    )
  jobs:
  - template: job-uhd-streaming-tests-beauty.yml
    parameters:
      testOS: ubuntu2004
      uhdSrcDir: $(Build.SourcesDirectory)/uhddev
      testLength: ${{ parameters.testLength }}
