//
// Copyright 2026 Ettus Research, a National Instruments Brand
//
// SPDX-License-Identifier: LGPL-3.0-or-later
//
// Module: ctrlport_to_ioport2_stream_tb
//
// Description:
//
//   Testbench for ctrlport_to_ioport2_stream.
//
//   The test drives CtrlPort requests through ctrlport_bfm and checks:
//     1) End-to-end register behavior against pcie_basic_regs.
//     2) ioport2 stream-request encoding produced by the bridge.
//

`default_nettype none


module ctrlport_to_ioport2_stream_tb #(
  parameter logic [31:0] SIGNATURE = 32'h1234_ABCD,
  parameter logic [31:0] CLK_FREQ  = 32'd200_000_000
);

  `include "test_exec.svh"

  import PkgTestExec::*;
  import ctrlport_pkg::*;
  import ctrlport_bfm_pkg::*;
  import ioport2_msg_pkg::*;

  localparam real CLK_PERIOD_NS = 10.0;

  localparam int REG_ADDR_WIDTH = 20;
  localparam int REG_DATA_WIDTH = 32;


  // Register offsets extracted from pcie_basic_regs.
  localparam logic [REG_ADDR_WIDTH-1:0] PCIE_FPGA_SIG_REG_ADDR        = 20'h00000;
  localparam logic [REG_ADDR_WIDTH-1:0] PCIE_FPGA_COUNTER_LO_REG_ADDR  = 20'h00004;
  localparam logic [REG_ADDR_WIDTH-1:0] PCIE_FPGA_COUNTER_HI_REG_ADDR  = 20'h00008;
  localparam logic [REG_ADDR_WIDTH-1:0] PCIE_FPGA_COUNTER_FREQ_ADDR   = 20'h0000C;
  localparam logic [REG_ADDR_WIDTH-1:0] PCIE_FPGA_SCRATCH_0_ADDR      = 20'h00010;
  localparam logic [REG_ADDR_WIDTH-1:0] PCIE_FPGA_SCRATCH_1_ADDR      = 20'h00014;
  localparam logic [REG_ADDR_WIDTH-1:0] PCIE_FPGA_MISC_STATUS_ADDR    = 20'h00020;
  localparam logic [REG_ADDR_WIDTH-1:0] PCIE_FPGA_USR_SIG_REG_ADDR     = 20'h00030;


  //---------------------------------------------------------------------------
  // Clocks and reset
  //---------------------------------------------------------------------------

  bit clk;
  bit rst;

  sim_clock_gen #(.PERIOD(CLK_PERIOD_NS), .AUTOSTART(0))
    clk_gen (.clk(clk), .rst(rst));


  //---------------------------------------------------------------------------
  // CtrlPort interface + BFM
  //---------------------------------------------------------------------------

  ctrlport_if cp_if (.clk(clk), .rst(rst));

  ctrlport_bfm cp_bfm = new(cp_if);


  //---------------------------------------------------------------------------
  // Bridge <-> endpoint stream wiring
  //---------------------------------------------------------------------------

  logic [63:0] regi_tdata;
  logic        regi_tvalid;
  logic        regi_tready;

  logic [63:0] rego_tdata;
  logic        rego_tvalid;
  logic        rego_tready;

  logic [REG_DATA_WIDTH-1:0] misc_status = 32'hD00D_CAFE;


  //---------------------------------------------------------------------------
  // DUT + endpoint
  //---------------------------------------------------------------------------

  ctrlport_to_ioport2_stream dut (
    .s_ctrlport             (cp_if),
    .regi_tdata             (regi_tdata),
    .regi_tvalid            (regi_tvalid),
    .regi_tready            (regi_tready),
    .rego_tdata             (rego_tdata),
    .rego_tvalid            (rego_tvalid),
    .rego_tready            (rego_tready)
  );


  // Arbitrarily use pcie_basic_regs as a simple endpoint to check the
  // correctness of the stream requests generated by the bridge.
  pcie_basic_regs #(
    .SIGNATURE(SIGNATURE),
    .CLK_FREQ (CLK_FREQ)
  ) pcie_basic_regs_i (
    .clk          (clk),
    .reset        (rst),
    .regi_tdata   (regi_tdata),
    .regi_tvalid  (regi_tvalid),
    .regi_tready  (regi_tready),
    .rego_tdata   (rego_tdata),
    .rego_tvalid  (rego_tvalid),
    .rego_tready  (rego_tready),
    .misc_status  (misc_status)
  );


  //---------------------------------------------------------------------------
  // Stream monitor for request-encoding checks
  //---------------------------------------------------------------------------

  typedef ioport2_msg_t req_msg_t;

  mailbox #(req_msg_t) req_msg_mb = new();

  // Populate req_msg_mb with decoded stream requests for checking
  // in test tasks.
  always @(posedge clk) begin
    req_msg_t msg;
    if (!rst && regi_tvalid && regi_tready) begin
      msg = req_msg_t'(regi_tdata);
      req_msg_mb.put(msg);
    end
  end


  //---------------------------------------------------------------------------
  // Helper tasks
  //---------------------------------------------------------------------------

  // Checks that a stream request message matches the expected encoding for a
  // given CtrlPort request.
  task automatic check_req_msg(
    input bit                         is_write,
    input logic [REG_ADDR_WIDTH-1:0]  reg_addr,
    input logic [REG_DATA_WIDTH-1:0]  req_data
  );
    req_msg_t msg;
    req_msg_mb.get(msg);

    `ASSERT_ERROR(msg.rd_response == 1'b0,
      $sformatf("Unexpected rd_response bit in request message: %0b", msg.rd_response));
    `ASSERT_ERROR(msg.wr_request == is_write,
      $sformatf("wr_request mismatch. got=%0b exp=%0b", msg.wr_request, is_write));
    `ASSERT_ERROR(msg.rd_request == !is_write,
      $sformatf("rd_request mismatch. got=%0b exp=%0b", msg.rd_request, !is_write));
    `ASSERT_ERROR(msg.half_word == 1'b0,
      $sformatf("half_word should be 0 for 32-bit ctrlport ops, got=%0b", msg.half_word));
    `ASSERT_ERROR(msg.address == reg_addr,
      $sformatf("address mismatch. got=0x%05h exp=0x%05h", msg.address, reg_addr));
    `ASSERT_ERROR(msg.data == req_data,
      $sformatf("data mismatch. got=0x%08h exp=0x%08h", msg.data, req_data));
  endtask

  task automatic cp_write_and_check(
    input logic [REG_ADDR_WIDTH-1:0] reg_addr,
    input logic [REG_DATA_WIDTH-1:0] wr_data
  );
    cp_bfm.write(reg_addr, wr_data, STS_OKAY);
    check_req_msg(1'b1, reg_addr, wr_data);
  endtask

  task automatic cp_read_and_check(
    input  logic [REG_ADDR_WIDTH-1:0] reg_addr,
    output logic [REG_DATA_WIDTH-1:0] rd_data
  );
    cp_bfm.read(reg_addr, rd_data, STS_OKAY);
    // ctrlport_bfm drives request.data as zero for reads.
    check_req_msg(1'b0, reg_addr, {REG_DATA_WIDTH{1'b0}});
  endtask


  //---------------------------------------------------------------------------
  // Tests - Validate register endpoint read/write capabilities
  //---------------------------------------------------------------------------

  task automatic test_id_and_status_regs();
    logic [REG_DATA_WIDTH-1:0] rd_data;

    test.start_test("ID and status registers");

    cp_read_and_check(PCIE_FPGA_SIG_REG_ADDR, rd_data);
    `ASSERT_ERROR(rd_data == SIGNATURE,
      $sformatf("SIGNATURE mismatch. got=0x%08h exp=0x%08h", rd_data, SIGNATURE));

    cp_read_and_check(PCIE_FPGA_COUNTER_FREQ_ADDR, rd_data);
    `ASSERT_ERROR(rd_data == CLK_FREQ,
      $sformatf("CLK_FREQ mismatch. got=0x%08h exp=0x%08h", rd_data, CLK_FREQ));

    cp_read_and_check(PCIE_FPGA_MISC_STATUS_ADDR, rd_data);
    `ASSERT_ERROR(rd_data == misc_status,
      $sformatf("misc_status mismatch. got=0x%08h exp=0x%08h", rd_data, misc_status));

    test.end_test();
  endtask

  task automatic test_scratch_regs();
    logic [REG_DATA_WIDTH-1:0] rd_data;

    test.start_test("Scratch register read/write");

    cp_read_and_check(PCIE_FPGA_SCRATCH_0_ADDR, rd_data);
    `ASSERT_ERROR(rd_data == {REG_DATA_WIDTH{1'b0}},
      $sformatf("scratch0 reset value mismatch. got=0x%08h", rd_data));

    cp_read_and_check(PCIE_FPGA_SCRATCH_1_ADDR, rd_data);
    `ASSERT_ERROR(rd_data == {REG_DATA_WIDTH{1'b0}},
      $sformatf("scratch1 reset value mismatch. got=0x%08h", rd_data));

    cp_write_and_check(PCIE_FPGA_SCRATCH_0_ADDR, 32'hDEAD_BEEF);
    cp_write_and_check(PCIE_FPGA_SCRATCH_1_ADDR, 32'hFACE_CAFE);

    cp_read_and_check(PCIE_FPGA_SCRATCH_0_ADDR, rd_data);
    `ASSERT_ERROR(rd_data == 32'hDEAD_BEEF,
      $sformatf("scratch0 value mismatch. got=0x%08h exp=0xDEADBEEF", rd_data));

    cp_read_and_check(PCIE_FPGA_SCRATCH_1_ADDR, rd_data);
    `ASSERT_ERROR(rd_data == 32'hFACE_CAFE,
      $sformatf("scratch1 value mismatch. got=0x%08h exp=0xFACECAFE", rd_data));

    test.end_test();
  endtask

  task automatic test_usr_signature_regs();
    logic [REG_DATA_WIDTH-1:0] rd_data;

    test.start_test("User signature register read/write");

    cp_write_and_check(PCIE_FPGA_USR_SIG_REG_ADDR + 20'h00000, 32'h0123_4567);
    cp_write_and_check(PCIE_FPGA_USR_SIG_REG_ADDR + 20'h00004, 32'h89AB_CDEF);
    cp_write_and_check(PCIE_FPGA_USR_SIG_REG_ADDR + 20'h00008, 32'h0BAD_F00D);
    cp_write_and_check(PCIE_FPGA_USR_SIG_REG_ADDR + 20'h0000C, 32'h55AA_33CC);

    cp_read_and_check(PCIE_FPGA_USR_SIG_REG_ADDR + 20'h00000, rd_data);
    `ASSERT_ERROR(rd_data == 32'h0123_4567,
      $sformatf("usr_signature[31:0] mismatch. got=0x%08h", rd_data));

    cp_read_and_check(PCIE_FPGA_USR_SIG_REG_ADDR + 20'h00004, rd_data);
    `ASSERT_ERROR(rd_data == 32'h89AB_CDEF,
      $sformatf("usr_signature[63:32] mismatch. got=0x%08h", rd_data));

    cp_read_and_check(PCIE_FPGA_USR_SIG_REG_ADDR + 20'h00008, rd_data);
    `ASSERT_ERROR(rd_data == 32'h0BAD_F00D,
      $sformatf("usr_signature[95:64] mismatch. got=0x%08h", rd_data));

    cp_read_and_check(PCIE_FPGA_USR_SIG_REG_ADDR + 20'h0000C, rd_data);
    `ASSERT_ERROR(rd_data == 32'h55AA_33CC,
      $sformatf("usr_signature[127:96] mismatch. got=0x%08h", rd_data));

    test.end_test();
  endtask

  task automatic test_counter_and_default();
    logic [REG_DATA_WIDTH-1:0] ctr_lo_0;
    logic [REG_DATA_WIDTH-1:0] ctr_lo_1;
    logic [REG_DATA_WIDTH-1:0] rd_data;

    test.start_test("Counter activity and default readback");

    cp_read_and_check(PCIE_FPGA_COUNTER_LO_REG_ADDR, ctr_lo_0);
    cp_read_and_check(PCIE_FPGA_COUNTER_HI_REG_ADDR, rd_data);
    cp_read_and_check(PCIE_FPGA_COUNTER_LO_REG_ADDR, ctr_lo_1);

    `ASSERT_ERROR(ctr_lo_1 != ctr_lo_0,
      $sformatf("counter low did not change. first=0x%08h second=0x%08h", ctr_lo_0, ctr_lo_1));

    cp_read_and_check(20'h001FC, rd_data);
    `ASSERT_ERROR(rd_data == {REG_DATA_WIDTH{1'b1}},
      $sformatf("default readback mismatch. got=0x%08h exp=0x%08h", rd_data,
                {REG_DATA_WIDTH{1'b1}}));

    test.end_test();
  endtask


  //---------------------------------------------------------------------------
  // Main test
  //---------------------------------------------------------------------------

  initial begin : main
    string tb_name;

    tb_name = $sformatf({"ctrlport_to_ioport2_stream_tb\n",
                         "SIGNATURE=0x%08h\n",
                         "CLK_FREQ=%0d"},
                         SIGNATURE, CLK_FREQ);

    test.start_tb(tb_name, 20ms);

    // Avoid extra simulation activity before this testbench acquires test_exec.
    clk_gen.start();

    cp_bfm.run();

    // Reset for 8 cycles, then wait for release.
    clk_gen.reset();
    @(negedge rst);

    test_id_and_status_regs();
    test_scratch_regs();
    test_usr_signature_regs();
    test_counter_and_default();

    test.end_tb(0);

    clk_gen.kill();
  end

endmodule : ctrlport_to_ioport2_stream_tb

`default_nettype wire
