#
# Copyright 2010 Ettus Research LLC
#

USRP_UHD_LA = $(top_srcdir)/lib/libusrp_uhd.la

GENERAL_CPPFLAGS = \
	-I$(top_srcdir)/include \
	$(BOOST_CPPFLAGS)

GENERAL_LDDFLAGS = \
	$(BOOST_LDFLAGS) \
	$(BOOST_THREAD_LIB)
