#
# Copyright 2018 Ettus Research, a National Instruments Company
#
# SPDX-License-Identifier: LGPL-3.0-or-later
#

##################################################
# DB COMMON Sources
##################################################
DB_COMMON_SRCS = $(abspath $(addprefix $(BASE_DIR)/n3xx/dboards/common/, \
PkgRegs.vhd \
sync/CrossTrigger.vhd \
sync/Pulser.vhd \
sync/TdcTop.vhd \
sync/TdcWrapper.vhd \
sync/TdcCore.edf \
sync/SyncRegsIfc.edf \
))
