#
# Copyright 2018 Ettus Research, A National Instruments Company
#
# SPDX-License-Identifier: LGPL-3.0-or-later
#

${'##################################################'}
# RFNoC Utility Sources
${'##################################################'}
RFNOC_BLOCK_${config.module_name.upper()}_SRCS = $(abspath $(addprefix $(BASE_DIR)/../lib/erfnoc/blocks/${destination}/, ${"\\"}
rfnoc_block_${config.module_name}.v ${"\\"}
noc_shell_${config.module_name}.v ${"\\"}
))
