#
# Copyright 2019 Ettus Research, a National Instruments Brand
#
# SPDX-License-Identifier: LGPL-3.0-or-later
#

RFNOC_BLOCK_DDC_SRCS += $(abspath $(addprefix $(BASE_DIR)/../lib/rfnoc/blocks/rfnoc_block_ddc/rfnoc_block_ddc_ss/, \
noc_shell_ddc_ss.v \
rfnoc_block_ddc_regs_ss.vh \
rfnoc_block_ddc_ss.v \
))
