#
# Copyright 2012-2013 Ettus Research LLC
#

##################################################
# FIFO Sources
##################################################
FIFO_SRCS = $(abspath $(addprefix $(BASE_DIR)/../lib/fifo/, \
axi_mux4.v \
axi_mux8.v \
axi_demux4.v \
axi_demux8.v \
axi_fifo_short.v \
axi_packet_gate.v \
axi_fifo.v \
axi_fifo64_to_fifo32.v \
axi_fifo32_to_fifo64.v \
axi_fifo_2clk.v \
axi_loopback.v \
))
