//
// Copyright 2026 Ettus Research, a National Instruments Brand
//
// SPDX-License-Identifier: LGPL-3.0-or-later
//
// Module: radio_control_regmap_utils.vh
//
// Description:
//
//   The constants in this file are autogenerated by XmlParse.
//

//===============================================================================
// A numerically ordered list of registers and their HDL source files
//===============================================================================

  // MISC_OUTPUTS         : 0x0 (radio_control_regs.sv)
  // MISC_INPUTS          : 0x4 (radio_control_regs.sv)
  // CH0_LED_ATR          : 0x10 (radio_control_regs.sv)
  // CH0_LED_STATUS       : 0x18 (radio_control_regs.sv)
  // CH1_LED_ATR          : 0x20 (radio_control_regs.sv)
  // CH1_LED_STATUS       : 0x28 (radio_control_regs.sv)
  // CH0_FP_GPIO_ATR      : 0x30 (radio_control_regs.sv)
  // CH0_FP_GPIO_STATUS   : 0x38 (radio_control_regs.sv)
  // CH1_FP_GPIO_ATR      : 0x40 (radio_control_regs.sv)
  // CH1_FP_GPIO_STATUS   : 0x48 (radio_control_regs.sv)
  // CH0_ADRV_GPIO_ATR    : 0x50 (radio_control_regs.sv)
  // CH0_ADRV_GPIO_STATUS : 0x58 (radio_control_regs.sv)
  // CH1_ADRV_GPIO_ATR    : 0x60 (radio_control_regs.sv)
  // CH1_ADRV_GPIO_STATUS : 0x68 (radio_control_regs.sv)
  // CH0_PATH_CTRL_ATR    : 0x70 (radio_control_regs.sv)
  // CH0_PATH_CTRL_STATUS : 0x78 (radio_control_regs.sv)
  // CH1_PATH_CTRL_ATR    : 0x80 (radio_control_regs.sv)
  // CH1_PATH_CTRL_STATUS : 0x88 (radio_control_regs.sv)

//===============================================================================
// RegTypes
//===============================================================================

  // CH_ADRV_GPIO_ATR Type (from radio_control_regs.sv)
  localparam CH_ADRV_GPIO_ATR_SIZE = 32;
  localparam CH_ADRV_GPIO_ATR_MASK = 32'hFF;
  localparam TRX_CTRL_0_SIZE = 1;  //CH_ADRV_GPIO_ATR:TRX_CTRL_0
  localparam TRX_CTRL_0_MSB  = 0;  //CH_ADRV_GPIO_ATR:TRX_CTRL_0
  localparam TRX_CTRL_0      = 0;  //CH_ADRV_GPIO_ATR:TRX_CTRL_0
  localparam TRX_CTRL_1_SIZE = 1;  //CH_ADRV_GPIO_ATR:TRX_CTRL_1
  localparam TRX_CTRL_1_MSB  = 1;  //CH_ADRV_GPIO_ATR:TRX_CTRL_1
  localparam TRX_CTRL_1      = 1;  //CH_ADRV_GPIO_ATR:TRX_CTRL_1
  localparam TRX_CTRL_2_SIZE = 1;  //CH_ADRV_GPIO_ATR:TRX_CTRL_2
  localparam TRX_CTRL_2_MSB  = 2;  //CH_ADRV_GPIO_ATR:TRX_CTRL_2
  localparam TRX_CTRL_2      = 2;  //CH_ADRV_GPIO_ATR:TRX_CTRL_2
  localparam TRX_CTRL_3_SIZE = 1;  //CH_ADRV_GPIO_ATR:TRX_CTRL_3
  localparam TRX_CTRL_3_MSB  = 3;  //CH_ADRV_GPIO_ATR:TRX_CTRL_3
  localparam TRX_CTRL_3      = 3;  //CH_ADRV_GPIO_ATR:TRX_CTRL_3
  localparam ADRV_GPIO_0_SIZE = 1;  //CH_ADRV_GPIO_ATR:ADRV_GPIO_0
  localparam ADRV_GPIO_0_MSB  = 4;  //CH_ADRV_GPIO_ATR:ADRV_GPIO_0
  localparam ADRV_GPIO_0      = 4;  //CH_ADRV_GPIO_ATR:ADRV_GPIO_0
  localparam ADRV_GPIO_1_SIZE = 1;  //CH_ADRV_GPIO_ATR:ADRV_GPIO_1
  localparam ADRV_GPIO_1_MSB  = 5;  //CH_ADRV_GPIO_ATR:ADRV_GPIO_1
  localparam ADRV_GPIO_1      = 5;  //CH_ADRV_GPIO_ATR:ADRV_GPIO_1
  localparam ADRV_GPIO_2_SIZE = 1;  //CH_ADRV_GPIO_ATR:ADRV_GPIO_2
  localparam ADRV_GPIO_2_MSB  = 6;  //CH_ADRV_GPIO_ATR:ADRV_GPIO_2
  localparam ADRV_GPIO_2      = 6;  //CH_ADRV_GPIO_ATR:ADRV_GPIO_2
  localparam ADRV_GPIO_3_SIZE = 1;  //CH_ADRV_GPIO_ATR:ADRV_GPIO_3
  localparam ADRV_GPIO_3_MSB  = 7;  //CH_ADRV_GPIO_ATR:ADRV_GPIO_3
  localparam ADRV_GPIO_3      = 7;  //CH_ADRV_GPIO_ATR:ADRV_GPIO_3

  // CH_FP_GPIO_ATR Type (from radio_control_regs.sv)
  localparam CH_FP_GPIO_ATR_SIZE = 32;
  localparam CH_FP_GPIO_ATR_MASK = 32'h3FF;
  localparam FP_DRIVE_VALUES_SIZE = 10;  //CH_FP_GPIO_ATR:FP_DRIVE_VALUES
  localparam FP_DRIVE_VALUES_MSB  =  9;  //CH_FP_GPIO_ATR:FP_DRIVE_VALUES
  localparam FP_DRIVE_VALUES      =  0;  //CH_FP_GPIO_ATR:FP_DRIVE_VALUES

  // CH_LED_ATR Type (from radio_control_regs.sv)
  localparam CH_LED_ATR_SIZE = 32;
  localparam CH_LED_ATR_MASK = 32'h13;
  localparam LED_TX_GREEN_SIZE = 1;  //CH_LED_ATR:LED_TX_GREEN
  localparam LED_TX_GREEN_MSB  = 0;  //CH_LED_ATR:LED_TX_GREEN
  localparam LED_TX_GREEN      = 0;  //CH_LED_ATR:LED_TX_GREEN
  localparam LED_TX_RED_SIZE = 1;  //CH_LED_ATR:LED_TX_RED
  localparam LED_TX_RED_MSB  = 1;  //CH_LED_ATR:LED_TX_RED
  localparam LED_TX_RED      = 1;  //CH_LED_ATR:LED_TX_RED
  localparam LED_RX_GREEN_SIZE = 1;  //CH_LED_ATR:LED_RX_GREEN
  localparam LED_RX_GREEN_MSB  = 4;  //CH_LED_ATR:LED_RX_GREEN
  localparam LED_RX_GREEN      = 4;  //CH_LED_ATR:LED_RX_GREEN

  // CH_PATH_CTRL_ATR Type (from radio_control_regs.sv)
  localparam CH_PATH_CTRL_ATR_SIZE = 32;
  localparam CH_PATH_CTRL_ATR_MASK = 32'h3;
  localparam CH_ENABLE_TXRX_TDR_SIZE = 1;  //CH_PATH_CTRL_ATR:CH_ENABLE_TXRX_TDR
  localparam CH_ENABLE_TXRX_TDR_MSB  = 0;  //CH_PATH_CTRL_ATR:CH_ENABLE_TXRX_TDR
  localparam CH_ENABLE_TXRX_TDR      = 0;  //CH_PATH_CTRL_ATR:CH_ENABLE_TXRX_TDR
  localparam CH_BYPASS_RX_SIZE = 1;  //CH_PATH_CTRL_ATR:CH_BYPASS_RX
  localparam CH_BYPASS_RX_MSB  = 1;  //CH_PATH_CTRL_ATR:CH_BYPASS_RX
  localparam CH_BYPASS_RX      = 1;  //CH_PATH_CTRL_ATR:CH_BYPASS_RX

//===============================================================================
// Register Group RADIO_CONTROL_REGS
//===============================================================================

  // MISC_OUTPUTS Register (from radio_control_regs.sv)
  localparam MISC_OUTPUTS = 'h0; // Register Offset
  localparam MISC_OUTPUTS_SIZE = 32;  // register width in bits
  localparam MISC_OUTPUTS_MASK = 32'h3;
  localparam ADRV9032_RESET_SIZE = 1;  //MISC_OUTPUTS:ADRV9032_RESET
  localparam ADRV9032_RESET_MSB  = 0;  //MISC_OUTPUTS:ADRV9032_RESET
  localparam ADRV9032_RESET      = 0;  //MISC_OUTPUTS:ADRV9032_RESET
  localparam ADRV9032_TEST_EN_SIZE = 1;  //MISC_OUTPUTS:ADRV9032_TEST_EN
  localparam ADRV9032_TEST_EN_MSB  = 1;  //MISC_OUTPUTS:ADRV9032_TEST_EN
  localparam ADRV9032_TEST_EN      = 1;  //MISC_OUTPUTS:ADRV9032_TEST_EN

  // MISC_INPUTS Register (from radio_control_regs.sv)
  localparam MISC_INPUTS = 'h4; // Register Offset
  localparam MISC_INPUTS_SIZE = 32;  // register width in bits
  localparam MISC_INPUTS_MASK = 32'h3;
  localparam ADRV_INTERRUPT_0_SIZE = 1;  //MISC_INPUTS:ADRV_INTERRUPT_0
  localparam ADRV_INTERRUPT_0_MSB  = 0;  //MISC_INPUTS:ADRV_INTERRUPT_0
  localparam ADRV_INTERRUPT_0      = 0;  //MISC_INPUTS:ADRV_INTERRUPT_0
  localparam ADRV_INTERRUPT_1_SIZE = 1;  //MISC_INPUTS:ADRV_INTERRUPT_1
  localparam ADRV_INTERRUPT_1_MSB  = 1;  //MISC_INPUTS:ADRV_INTERRUPT_1
  localparam ADRV_INTERRUPT_1      = 1;  //MISC_INPUTS:ADRV_INTERRUPT_1

  // CH0_LED_ATR Register (from radio_control_regs.sv)
  localparam CH0_LED_ATR = 'h10; // Register Offset
  localparam CH0_LED_ATR_SIZE = 32;  // register width in bits

  // CH0_LED_STATUS Register (from radio_control_regs.sv)
  localparam CH0_LED_STATUS = 'h18; // Register Offset
  localparam CH0_LED_STATUS_SIZE = 32;  // register width in bits

  // CH1_LED_ATR Register (from radio_control_regs.sv)
  localparam CH1_LED_ATR = 'h20; // Register Offset
  localparam CH1_LED_ATR_SIZE = 32;  // register width in bits

  // CH1_LED_STATUS Register (from radio_control_regs.sv)
  localparam CH1_LED_STATUS = 'h28; // Register Offset
  localparam CH1_LED_STATUS_SIZE = 32;  // register width in bits

  // CH0_FP_GPIO_ATR Register (from radio_control_regs.sv)
  localparam CH0_FP_GPIO_ATR = 'h30; // Register Offset
  localparam CH0_FP_GPIO_ATR_SIZE = 32;  // register width in bits

  // CH0_FP_GPIO_STATUS Register (from radio_control_regs.sv)
  localparam CH0_FP_GPIO_STATUS = 'h38; // Register Offset
  localparam CH0_FP_GPIO_STATUS_SIZE = 32;  // register width in bits

  // CH1_FP_GPIO_ATR Register (from radio_control_regs.sv)
  localparam CH1_FP_GPIO_ATR = 'h40; // Register Offset
  localparam CH1_FP_GPIO_ATR_SIZE = 32;  // register width in bits

  // CH1_FP_GPIO_STATUS Register (from radio_control_regs.sv)
  localparam CH1_FP_GPIO_STATUS = 'h48; // Register Offset
  localparam CH1_FP_GPIO_STATUS_SIZE = 32;  // register width in bits

  // CH0_ADRV_GPIO_ATR Register (from radio_control_regs.sv)
  localparam CH0_ADRV_GPIO_ATR = 'h50; // Register Offset
  localparam CH0_ADRV_GPIO_ATR_SIZE = 32;  // register width in bits

  // CH0_ADRV_GPIO_STATUS Register (from radio_control_regs.sv)
  localparam CH0_ADRV_GPIO_STATUS = 'h58; // Register Offset
  localparam CH0_ADRV_GPIO_STATUS_SIZE = 32;  // register width in bits

  // CH1_ADRV_GPIO_ATR Register (from radio_control_regs.sv)
  localparam CH1_ADRV_GPIO_ATR = 'h60; // Register Offset
  localparam CH1_ADRV_GPIO_ATR_SIZE = 32;  // register width in bits

  // CH1_ADRV_GPIO_STATUS Register (from radio_control_regs.sv)
  localparam CH1_ADRV_GPIO_STATUS = 'h68; // Register Offset
  localparam CH1_ADRV_GPIO_STATUS_SIZE = 32;  // register width in bits

  // CH0_PATH_CTRL_ATR Register (from radio_control_regs.sv)
  localparam CH0_PATH_CTRL_ATR = 'h70; // Register Offset
  localparam CH0_PATH_CTRL_ATR_SIZE = 32;  // register width in bits

  // CH0_PATH_CTRL_STATUS Register (from radio_control_regs.sv)
  localparam CH0_PATH_CTRL_STATUS = 'h78; // Register Offset
  localparam CH0_PATH_CTRL_STATUS_SIZE = 32;  // register width in bits

  // CH1_PATH_CTRL_ATR Register (from radio_control_regs.sv)
  localparam CH1_PATH_CTRL_ATR = 'h80; // Register Offset
  localparam CH1_PATH_CTRL_ATR_SIZE = 32;  // register width in bits

  // CH1_PATH_CTRL_STATUS Register (from radio_control_regs.sv)
  localparam CH1_PATH_CTRL_STATUS = 'h88; // Register Offset
  localparam CH1_PATH_CTRL_STATUS_SIZE = 32;  // register width in bits
