#
# Copyright 2013 Ettus Research LLC
# Copyright 2016 Ettus Research, a National Instruments Company
#
# SPDX-License-Identifier: LGPL-3.0-or-later
#

##################################################
# Packet Processing Sources
##################################################
PACKET_PROC_SRCS = $(abspath $(addprefix $(BASE_DIR)/../lib/packet_proc/, \
chdr_chunker.v \
chdr_dechunker.v \
cvita_dest_lookup.v \
ip_hdr_checksum.v \
arm_deframer.v \
arp_responder/arp_responder.vhd \
))

