#
# Copyright 2010 Ettus Research LLC
#

##################################################
# Extram Sources
##################################################
EXTRAM_SRCS = $(abspath $(addprefix $(BASE_DIR)/../extram/, \
wb_zbt16_b.v \
))
