#
# Copyright 2021 Ettus Research, a National Instruments Brand
#
# SPDX-License-Identifier: LGPL-3.0-or-later
#
# Description:
#
# Automated x4xx openembedded build on Azure DevOps
#
# This pipeline builds the following openembedded targets:
# - UHD
# - UHD FPGA images
# - MPMD
#
# It also runs UHD unit tests and publishes their results.

trigger:
  branches:
    include:
    - master
  paths:
    include:
      - .ci
      - host
      - mpm
      - images/manifest.txt

pr:
  branches:
    include:
    - master
  paths:
    include:
      - .ci
      - host
      - mpm
      - images/manifest.txt

resources:
  repositories:
    - repository: meta-ettus
      type: github
      name: EttusResearch/meta-ettus-dev
      endpoint: EttusResearch
      ref: zeus-ci
  pipelines:
    - pipeline: usrp-kas-pipeline
      source: 'usrp-kas'

variables:
  AUTO_CONF: $(Agent.BuildDirectory)/auto.conf

jobs:
  - template: .ci/templates/job_build_package.yml@meta-ettus
    parameters:
      machines:
        - x4xx
      checkout_meta_ettus: true
      targets:
        - uhd:do_package_write_ipk
        - uhd:do_run_tests
        - mpmd:do_package_write_ipk
        - gnuradio:do_package_write_ipk
        - gr-ettus:do_package_write_ipk
      auto_conf: $AUTO_CONF
      prebuild_steps:
        - script: rm -f $AUTO_CONF
        - template: .ci/templates/oe_localconf_externalsrc.yml@meta-ettus
          parameters:
            conf_file: $AUTO_CONF
            repository: self
            package_paths:
              - package: uhd
                path: host
              - package: mpmd
                path: mpm
