#
# Copyright 2021 Ettus Research, a National Instruments Brand
#
# SPDX-License-Identifier: LGPL-3.0-or-later
#

parameters:
- name: release_binaries
  type: boolean
  default: false
- name: testLength
  type: string
  values:
  - 'smoke'
  - 'full'
  - 'stress'
  default: 'smoke'
- name: run_streaming_tests
  type: boolean
  default: False

trigger:
  batch: true
  branches:
    include:
    - master
  paths:
    include:
    - host
    - .ci
    - images/manifest.txt
    exclude:
    - .ci/docker
    - host/docs
    - host/LICENSE
    - host/README.md

pr: none

extends:
  template: templates/stages-uhd-pipeline.yml
  parameters:
    release_binaries: ${{ parameters.release_binaries }}
    testLength: ${{ parameters.testLength }}
    run_streaming_tests: ${{ parameters.run_streaming_tests }}
