#
# Copyright 2021 Ettus Research, a National Instruments Brand
#
# SPDX-License-Identifier: LGPL-3.0-or-later
#

parameters:
  # Force enable/disable modules, examples:
  #
  # Force-enable/disable UHD builds...
  # ... for all OS:  uhd.build.all
  # ... for Linux:   uhd.build.linux
  # ... for Windows: uhd.build.windows
  # ... for macOS:   uhd.build.mac
  #
  # Force-enable/disable MPM builds...
  # ... for all devs: mpm.build.all
  #
  # Force-enable/disable FPGA images builds...
  # ... all FPGAs:   fpga.usrp3.all
  # ... E31X FPGAs:  fpga.usrp3.e31x
  # ... E320 FPGAs:  fpga.usrp3.e320
  # ... N3XX FPGAs:  fpga.usrp3.n3xx
  # ... X4XX FPGAs:  fpga.usrp3.x4xx
  # ... X410 FPGAs:  fpga.usrp3.x410
  # ... X440 FPGAs:  fpga.usrp3.x440
  #
  # Force-enable/disable tests...
  # ... Devtests: devtest.all
  # ... Streaming tests: hw.streaming.all
  # ... RF tests: hw.rf.all
  #
  # For more examples, see tools/changeset_testlist.yaml
- name: add_tests
  displayName: Force-enable modules
  type: string
  default: "none"
- name: remove_tests
  displayName: Force-disable modules
  type: string
  default: "none"
- name: skip_rule_checking
  displayName: Skip rule checking (execute "Force-enable modules" only)
  type: boolean
  default: False
- name: custom_boost_version
  type: boolean
  displayName: Use custom boost version
  default: false
- name: custom_boost_version_url
  type: string
  displayName: Custom Boost URL
  default: 'https://boostorg.jfrog.io/artifactory/main/release/1.76.0/source/boost_1_76_0.tar.bz2'
- name: release_binaries
  type: boolean
  displayName: Set release mode for installers
  default: false
- name: testLength
  type: string
  values:
  - 'smoke'
  - 'full'
  - 'stress'
  displayName: Test Length
  default: 'smoke'
- name: create_sbom
  type: boolean
  displayName: Create SBOM for filesystem images
  default: false
- name: build_sdk
  type: boolean
  displayName: Build embedded image SDKs
  default: false
- name: cache_sstate
  type: boolean
  displayName: Use sstate cache for embedded builds
  default: true
- name: build_e310_sg1
  type: boolean
  displayName: Build e310_sg1 filesystem image
  default: true
- name: build_e310_sg3
  type: boolean
  displayName: Build e310_sg3 filesystem image
  default: true
- name: build_e320
  type: boolean
  displayName: Build e320 filesystem image
  default: true
- name: build_n3xx
  type: boolean
  displayName: Build n3xx filesystem image
  default: true
- name: build_x4xx
  type: boolean
  displayName: Build x4xx filesystem image
  default: true
- name: fpga_imgs_source
  type: string
  values:
  - 'files.ettus.com (Public)'
  - 'Internal Repo'
  - 'Mono Pipeline'
  - 'Mono Pipeline PR'
  - 'FPGA Pipeline'
  displayName: FPGA Images Source
  default: 'Mono Pipeline'
  # FPGA Parameters
- name: clean_ip_build
  type: boolean
  displayName: Clean IP Build
  default: false
- name: num_ip_jobs
  type: number
  default: 5
  displayName: Number of parallel IP jobs
- name: package_and_publish_images
  type: boolean
  displayName: Package & Publish Images
  default: false
  # Package access: This controls from where we download the FPGA images, if we
  # are not building them.
- name: package_access
  type: string
  values:
  - 'Internal'
  - 'files.ettus.com (Public)'
  displayName: Published Package Access
  default: 'Internal'
# Requested X410 targets
- name: x410_targets_matrix
  type: object
  displayName: X410 Targets
  default:
    X410_UC_200:
      image_core: x410_UC_200_rfnoc_image_core.yml
      image_core_name: usrp_x410_fpga_UC_200
      target_name: X410
      artifact_name: X410_UC_200
      timeout: 720
      max_attempts: 2
    X410_X4_200:
      image_core: x410_X4_200_rfnoc_image_core.yml
      image_core_name: usrp_x410_fpga_X4_200
      target_name: X410
      artifact_name: X410_X4_200
      timeout: 720
      max_attempts: 2
    X410_CG_400:
      image_core: x410_CG_400_rfnoc_image_core.yml
      image_core_name: usrp_x410_fpga_CG_400
      target_name: X410
      artifact_name: X410_CG_400
      timeout: 720
      max_attempts: 2
    X410_FFT_BLOCK_TEST:
      image_core: ../../../../host/tests/rfnoc_block_tests_on_target/x410_fft_block_test.yml
      image_core_name: usrp_x410_fpga_fft_block_test
      target_name: X410
      artifact_name: X410_FFT_BLOCK_TEST
      timeout: 720
      max_attempts: 2
- name: x440_targets_matrix
  type: object
  displayName: X440 Targets
  default:
    X440_CG_1600:
      image_core: x440_CG_1600_rfnoc_image_core.yml
      image_core_name: usrp_x440_fpga_CG_1600
      target_name: X440
      artifact_name: X440_CG_1600
      timeout: 720
      max_attempts: 2
    X440_CG_400:
      image_core: x440_CG_400_rfnoc_image_core.yml
      image_core_name: usrp_x440_fpga_CG_400
      target_name: X440
      artifact_name: X440_CG_400
      timeout: 720
      max_attempts: 2
    X440_X4_1600:
      image_core: x440_X4_1600_rfnoc_image_core.yml
      image_core_name: usrp_x440_fpga_X4_1600
      target_name: X440
      artifact_name: X440_X4_1600
      timeout: 720
      max_attempts: 2
    X440_X4_400:
      image_core: x440_X4_400_rfnoc_image_core.yml
      image_core_name: usrp_x440_fpga_X4_400
      target_name: X440
      artifact_name: X440_X4_400
      timeout: 720
      max_attempts: 2
    X440_X4_200:
      image_core: x440_X4_200_rfnoc_image_core.yml
      image_core_name: usrp_x440_fpga_X4_200
      target_name: X440
      artifact_name: X440_X4_200
      timeout: 720
      max_attempts: 2


trigger: none

pr:
  branches:
    include:
    - master
    - UHD-*
  paths:
    include:
    - host
    - mpm
    - fpga
    - .ci
    - images/manifest.txt
    exclude:
    - .ci/docker
    - host/docs
    - host/LICENSE
    - host/README.md
  drafts: false

extends:
  template: templates/stages-uhd-pipeline.yml
  parameters:
    add_tests: ${{ parameters.add_tests }}
    remove_tests: ${{ parameters.remove_tests }}
    skip_rule_checking: ${{ parameters.skip_rule_checking }}
    custom_boost_version: ${{ parameters.custom_boost_version }}
    custom_boost_version_url: ${{ parameters.custom_boost_version_url }}
    release_binaries: ${{ parameters.release_binaries }}
    testLength: ${{ parameters.testLength }}
    create_sbom: ${{ parameters.create_sbom }}
    build_sdk: ${{ parameters.build_sdk }}
    cache_sstate: ${{ parameters.cache_sstate }}
    build_e310_sg1: ${{ parameters.build_e310_sg1 }}
    build_e310_sg3: ${{ parameters.build_e310_sg3 }}
    build_e320: ${{ parameters.build_e320 }}
    build_n3xx: ${{ parameters.build_n3xx }}
    build_x4xx: ${{ parameters.build_x4xx }}
    fpga_imgs_source: ${{ parameters.fpga_imgs_source }}
    # FPGA parameters
    clean_ip_build: ${{ parameters.clean_ip_build }}
    publish_int_files: true
    package_and_publish_images: ${{ parameters.package_and_publish_images }}
    package_access: ${{ parameters.package_access }}
    x410_targets_matrix: ${{ parameters.x410_targets_matrix }}
    x440_targets_matrix: ${{ parameters.x440_targets_matrix }}
