.TH "usrp_n2xx_simple_net_burner" 1 "3.5.1" UHD "User Commands"
.SH NAME
usrp_n2xx_simple_net_burner - USRP N-Series FPGA/Firmware Burner
.SH DESCRIPTION
Burn firmware and FPGA images onto connected USRP N-Series devices. The
program takes an IP address as an argument, queries the USRP device to
identify which model and revision it is, and burns the appropriate images
over Ethernet.
.SH SYNOPSIS
.B  usrp_n2xx_simple_net_burner [OPTIONS]
.SH OPTIONS
This program works best when only an IP address is specified.
.IP "Device IP Address:"
--addr=\fI"Address"\fR (default: 192.168.10.2)
.IP "This help information:"
--help
.IP "Custom Firmware Filepath:"
--fw=\fI"filepath"\fR
.IP "Custom FPGA Filepath:"
--fpga=\fI"filepath"\fR
.IP "Don't burn firmware:"
--no_fw
.IP "Don't burn FPGA:"
--no_fpga
.IP "Automatically reboot USRP device after burning"
--auto_reboot
.IP "List all USRP devices without burning"
--list
.SH EXAMPLES
.SS Selecting a USRP device with a non-standard IP address
.sp
usrp_n2xx_simple_net_burner --addr=192.168.10.3
.ft
.fi
.SH SEE ALSO
UHD documentation:
.B http://files.ettus.com/uhd_docs/manual/html/index.html
.LP
GR-UHD documentation:
.B http://gnuradio.org/doc/doxygen/page_uhd.html
.LP
Other UHD programs:
.sp
uhd_images_downloader(1) usrp2_card_burner(1)
.SH AUTHOR
This manual page was written by Nicholas Corgan
for the Debian project (but may be used by others).
.SH COPYRIGHT
Copyright (c) 2012 Ettus Research LLC
.LP
This program is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.
.LP
This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.
