#
# Copyright 2018 Ettus Research, A National Instruments Company
#
# SPDX-License-Identifier: LGPL-3.0-or-later
#

##################################################
# RFNoC Utility Sources
##################################################
RFNOC_XPORT_SRCS = $(abspath $(addprefix $(BASE_DIR)/../lib/rfnoc/xport/, \
chdr_xport_adapter_generic.v \
eth_ipv4_chdr64_adapter.v \
eth_ipv4_chdr64_dispatch.v \
eth_interface.v \
eth_internal.v \
))
