#
# Copyright 2026 Ettus Research, a National Instruments Brand
#
# SPDX-License-Identifier: LGPL-3.0-or-later
#

include $(BASE_DIR)/../lib/rfnoc/blocks/rfnoc_block_duc/rfnoc_block_duc_ss/Makefile.srcs
include $(BASE_DIR)/../lib/rfnoc/blocks/rfnoc_block_duc/rfnoc_block_duc_ms/Makefile.srcs

RFNOC_BLOCK_DUC_SRCS += $(abspath $(addprefix $(BASE_DIR)/../lib/rfnoc/blocks/rfnoc_block_duc/, \
rfnoc_block_duc.sv \
))
