//
// Copyright 2023 Ettus Research, a National Instruments Brand
//
// SPDX-License-Identifier: LGPL-3.0-or-later
//
// Header: rfnoc_image_core.vh (for x440)
//
// Description:
//
//   This is the header file for the RFNoC Image Core.
//
//   This file was automatically generated by the RFNoC image builder tool.
//   Re-running that tool will overwrite this file!
//
// Source: x440_400_rfnoc_image_core.yml
//

`define CHDR_WIDTH     512
`define RFNOC_PROTOVER { 8'd1, 8'd0 }
