#
# Copyright 2012-2013 Ettus Research LLC
# Copyright 2016 Ettus Research, a National Instruments Company
#
# SPDX-License-Identifier: LGPL-3.0-or-later
#

##################################################
# FIFO 200 Sources
##################################################
FIFO_200_SRCS = $(abspath $(addprefix $(BASE_DIR)/../lib/fifo_200/, \
axi_fifo_legacy.v \
))
