#
# Copyright 2019 Ettus Research, A National Instruments Company
#
# SPDX-License-Identifier: LGPL-3.0-or-later
#

RFNOC_OOT_SRCS += $(abspath $(addprefix $(BASE_DIR)/../lib/rfnoc/blocks/rfnoc_block_fir_filter/, \
noc_shell_fir_filter.v \
rfnoc_fir_filter_regs.vh \
rfnoc_fir_filter_core.v \
rfnoc_block_fir_filter.v \
))
