#
# Copyright 2025 Ettus Research, a National Instruments Brand
#
# SPDX-License-Identifier: LGPL-3.0-or-later
#
# Description:
#
#   Execute only a subset of FPGA based stages of full mono pipeline.
#

parameters:
- name: run_testbenches
  type: boolean
  displayName: Run Testbenches
  default: false
- name: clean_ip_build
  type: boolean
  displayName: Clean IP Build
  default: false
- name: num_ip_jobs
  type: number
  default: 5
  displayName: Number of parallel IP jobs
- name: build_x3x0
  type: boolean
  displayName: Build X3x0
  default: false
- name: build_n3xx
  type: boolean
  displayName: Build N3xx
  default: false
- name: build_e31x
  type: boolean
  displayName: Build E31x
  default: false
- name: build_e32x
  type: boolean
  displayName: Build E32x
  default: false
- name: build_x410
  type: boolean
  displayName: Build X410
  default: false
- name: build_x440
  type: boolean
  displayName: Build X440
  default: false
- name: build_x4xx_cplds
  type: boolean
  displayName: Build X4xx CPLDs
  default: false
- name: build_regmaps
  type: boolean
  displayName: Build Register Maps
  default: false
- name: package_and_publish_images
  type: boolean
  displayName: Package & Publish Images
  default: false
- name: package_access
  type: string
  values:
  - 'Internal'
  - 'files.ettus.com (Public)'
  displayName: Published Package Access
  default: 'Internal'
# Requested X410 targets
- name: x410_targets_matrix
  displayName: X410 Targets
  type: object
  default:
    X410_X4_200:
      image_core: x410_X4_200_rfnoc_image_core.yml
      image_core_name: usrp_x410_fpga_X4_200
      target_name: X410
      artifact_name: X410_X4_200
      timeout: 720
      max_attempts: 2
    X410_UC_200:
      image_core: x410_UC_200_rfnoc_image_core.yml
      image_core_name: usrp_x410_fpga_UC_200
      target_name: X410
      artifact_name: X410_UC_200
      timeout: 720
      max_attempts: 2
    X410_X4_400:
      image_core: x410_X4_400_rfnoc_image_core.yml
      image_core_name: usrp_x410_fpga_X4_400
      target_name: X410
      artifact_name: X410_X4_400
      timeout: 720
      max_attempts: 2
    X410_CG_400:
      image_core: x410_CG_400_rfnoc_image_core.yml
      image_core_name: usrp_x410_fpga_CG_400
      target_name: X410
      artifact_name: X410_CG_400
      timeout: 720
      max_attempts: 2
- name: x440_targets_matrix
  displayName: X440 Targets
  type: object
  default:
    X440_CG_1600:
      image_core: x440_CG_1600_rfnoc_image_core.yml
      image_core_name: usrp_x440_fpga_CG_1600
      target_name: X440
      artifact_name: X440_CG_1600
      timeout: 720
      max_attempts: 2
    X440_CG_400:
      image_core: x440_CG_400_rfnoc_image_core.yml
      image_core_name: usrp_x440_fpga_CG_400
      target_name: X440
      artifact_name: X440_CG_400
      timeout: 720
      max_attempts: 2
    X440_X4_1600:
      image_core: x440_X4_1600_rfnoc_image_core.yml
      image_core_name: usrp_x440_fpga_X4_1600
      target_name: X440
      artifact_name: X440_X4_1600
      timeout: 720
      max_attempts: 2
    X440_X4_400:
      image_core: x440_X4_400_rfnoc_image_core.yml
      image_core_name: usrp_x440_fpga_X4_400
      target_name: X440
      artifact_name: X440_X4_400
      timeout: 720
      max_attempts: 2
    X440_X4_200:
      image_core: x440_X4_200_rfnoc_image_core.yml
      image_core_name: usrp_x440_fpga_X4_200
      target_name: X440
      artifact_name: X440_X4_200
      timeout: 720
      max_attempts: 2

trigger: none
pr: none

extends:
  template: ../../.ci/templates/stages-uhd-pipeline.yml
  parameters:
    add_tests: ${{
        format(
          '{0};{1};{2};{3};{4};{5};{6};{7};{8};',
          iif(parameters.run_testbenches,'fpga.usrp3.testbenches',''),
          iif(parameters.build_x3x0,'fpga.usrp3.x3xx',''),
          iif(parameters.build_n3xx,'fpga.usrp3.n3xx',''),
          iif(parameters.build_e31x,'fpga.usrp3.e31x',''),
          iif(parameters.build_e32x,'fpga.usrp3.e32x',''),
          iif(parameters.build_x410,'fpga.usrp3.x410',''),
          iif(parameters.build_x440,'fpga.usrp3.x440',''),
          iif(parameters.build_x4xx_cplds,'fpga.usrp3.cpld.x4xx',''),
          iif(parameters.build_regmaps,'fpga.usrp3.regmaps','')
        )
      }}
    skip_rule_checking: true
    # FPGA parameters
    clean_ip_build: ${{ parameters.clean_ip_build }}
    publish_int_files: true
    x410_targets_matrix: ${{ parameters.x410_targets_matrix }}
    x440_targets_matrix: ${{ parameters.x440_targets_matrix }}
    package_and_publish_images: ${{ parameters.package_and_publish_images }}
    package_access: ${{ parameters.package_access }}
