#
# Copyright 2022 Ettus Research, a National Instruments Brand
#
# SPDX-License-Identifier: LGPL-3.0-or-later
#
# Description:
#
#   This pipeline is used to build FPGAs and run testbenches as CI
#   from commits in master.
#
#   See https://aka.ms/yaml for pipeline YAML documentation.
#

parameters:
- name: run_testbenches
  type: boolean
  displayName: Run Testbenches
  default: false
- name: clean_ip_build
  type: boolean
  displayName: Clean IP Build
  default: true
- name: num_ip_jobs
  type: number
  default: 5
  displayName: Number of parallel IP jobs
- name: package_and_publish_images
  type: boolean
  displayName: Package & Publish Images
  default: true
- name: package_access
  type: string
  values:
  - 'Internal'
  - 'files.ettus.com (Public)'
  displayName: Published Package Access
  default: 'Internal'
- name: skip_analyze_changeset
  type: boolean
  displayName: Skip Analyze Changeset
  default: true
- name: build_x3x0
  type: boolean
  displayName: Build X3x0
  default: true
- name: build_n3xx
  type: boolean
  displayName: Build N3xx
  default: true
- name: build_e31x
  type: boolean
  displayName: Build E31x
  default: true
- name: build_e32x
  type: boolean
  displayName: Build E32x
  default: true
- name: build_x410
  type: boolean
  displayName: Build X410
  default: true
- name: build_x440
  type: boolean
  displayName: Build X440
  default: true

trigger:
  batch: true
  branches:
    include:
    - master
  paths:
    include:
    - fpga/usrp3/lib
    - fpga/usrp3/top
    - fpga/.ci

pr: none

schedules:
- cron: "0 18 * * Sun"
  displayName: Weekly FPGA CI Build master branch
  branches:
    include:
    - master
  always: true

extends:
  template: templates/stages-fpga-pipeline.yml
  parameters:
    run_testbenches: ${{ parameters.run_testbenches }}
    clean_ip_build: ${{ parameters.clean_ip_build }}
    package_and_publish_images: ${{ parameters.package_and_publish_images }}
    package_access: ${{ parameters.package_access }}
    skip_analyze_changeset: ${{ parameters.skip_analyze_changeset }}
    build_x3x0: ${{ parameters.build_x3x0 }}
    build_n3xx: ${{ parameters.build_n3xx }}
    build_e31x: ${{ parameters.build_e31x }}
    build_e32x: ${{ parameters.build_e32x }}
    build_x410: ${{ parameters.build_x410 }}
    build_x440: ${{ parameters.build_x440 }}
