.TH UHD_ADC_SELF_CAL "1" "July 2021" "uhd_adc_self_cal 4.1" "User Commands"
.SH NAME
uhd_adc_self_cal \- invoke calibration in some UHD devices.
.SH DESCRIPTION
.SS "UHD ADC self calibration Allowed options:"
.TP
\fB\-\-help\fR
help message
.TP
\fB\-\-version\fR
print the version string and exit
.TP
\fB\-\-args\fR arg
device address args, using usual UHD device selection specifiers.
