#
# Copyright 2026 Ettus Research, a National Instruments Brand
#
# SPDX-License-Identifier: LGPL-3.0-or-later
#

CTRLPORT_SPI_ADRV_SRCS = $(abspath $(addprefix $(BASE_DIR)/../lib/control/, \
axis_spi.sv \
ctrlport_spi_adrv_pkg.sv \
ctrlport_spi_adrv.sv \
))
