#
# Copyright 2012 Ettus Research LLC
#

##################################################
# FIFO Sources
##################################################
CUSTOM_SRCS = $(abspath $(addprefix $(BASE_DIR)/../custom/, \
custom_dsp_rx.v \
custom_dsp_tx.v \
))
