#
# Copyright 2026 Ettus Research, a National Instruments Brand
#
# SPDX-License-Identifier: LGPL-3.0-or-later
#

##################################################
# HB Filter Sources
##################################################
HB_FILTER_SRCS = $(abspath $(addprefix $(BASE_DIR)/../lib/dsp/hb_filter/, \
axis_hb_utils_pkg.sv \
axis_hb_cascade_decim.sv \
axis_hb_decim_fir.sv \
axis_hb_intp_fir.sv \
axis_upsamp_x2.sv \
axis_upsamp_x2_ser.sv \
axis_upsamp_x2_par.sv \
axis_hb_cascade_intp.sv \
axis_hb_intp_stage.sv \
axis_hb_decim_stage.sv \
))
