//-----------------------------------------------------------------------------
// File: XmlSvPkgFPGA_GPIO_REGMAP.sv
// Author: Autogenerated by XmlParse
// Original Project: --
// Date: --
//-----------------------------------------------------------------------------
// (c) 2025 National Instruments Corporation. All Rights Reserved.
//-----------------------------------------------------------------------------
// Purpose:
//   The constants in this file are autogenerated by XmlParse.
//-----------------------------------------------------------------------------

package XmlSvPkgFPGA_GPIO_REGMAP;

//===============================================================================
// A numerically ordered list of registers and their HDL source files
//===============================================================================

  // SYNC_INJECTION_WINDOW : 0x0 (db_gpio_interface.sv)

//===============================================================================
// Register Group FPGA_GPIO_WINDOW
//===============================================================================

  // SYNC_INJECTION_WINDOW Window (from db_gpio_interface.sv)
  localparam kSYNC_INJECTION_WINDOW = 'h0; // Window Offset
  localparam kSYNC_INJECTION_WINDOWSize = 'h1000;  // size in bytes

 typedef struct packed {
  logic [4095:0] Rsvd4095_0;  // [4095:   0] 4096 bit spacer for empty reg
 } SYNC_INJECTION_WINDOW;

//===============================================================================
// RegTypes
//===============================================================================

endpackage : XmlSvPkgFPGA_GPIO_REGMAP
